//! Generated and call-site documentation that must agree with the types it
//! documents (CONTRACT.md §27.4 rule 5, §29.2, §21.3.1; contract 1.59 §34.3
//! row R-28).
//!
//! The management surface is generated by `tools/gen_management.py`, so these
//! assertions read the committed output: a generator that regresses fails
//! here and in the `--check` drift job alike.

use std::fs;
use std::path::Path;

fn read(relative: &str) -> String {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(relative);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

/// The `///` lines immediately above `item`, joined into one line of prose.
fn doc_above(source: &str, item: &str) -> String {
    let at = source
        .find(item)
        .unwrap_or_else(|| panic!("{item} not found"));
    let mut lines: Vec<&str> = source[..at]
        .lines()
        .rev()
        .skip_while(|l| l.trim().is_empty())
        .take_while(|l| {
            let t = l.trim_start();
            t.starts_with("///") || t.starts_with("#[")
        })
        .filter(|l| l.trim_start().starts_with("///"))
        .map(|l| l.trim_start().trim_start_matches("///").trim())
        .collect();
    lines.reverse();
    lines.join(" ")
}

/// The body of `pub struct name { … }` in `source`.
fn struct_body<'a>(source: &'a str, name: &str) -> &'a str {
    let head = format!("pub struct {name} {{");
    let at = source
        .find(&head)
        .unwrap_or_else(|| panic!("{head} not found"));
    let rest = &source[at..];
    &rest[..rest.find("\n}\n").expect("the struct closes")]
}

#[test]
fn a_replacement_with_optional_members_does_not_call_every_field_required() {
    let models = read("src/management/models.rs");
    let ops_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src/management/ops");
    let mut checked = 0;
    for entry in fs::read_dir(&ops_dir).unwrap() {
        let path = entry.unwrap().path();
        let source = fs::read_to_string(&path).unwrap();
        for (at, _) in source.match_indices("**This is a replacement, not a patch**") {
            let rest = &source[at..];
            let signature_at = rest.find("pub async fn").expect("an operation follows");
            let signature =
                &rest[signature_at..rest[signature_at..].find('{').unwrap() + signature_at];
            let Some(body_at) = signature.find("body: &models::") else {
                continue;
            };
            let body_type: String = signature[body_at + "body: &models::".len()..]
                .chars()
                .take_while(|c| c.is_alphanumeric() || *c == '_')
                .collect();
            let has_optional = struct_body(&models, &body_type).contains(": Option<");
            let doc: String = rest[..signature_at]
                .lines()
                .map(|l| l.trim_start().trim_start_matches("///").trim())
                .collect::<Vec<_>>()
                .join(" ");
            if has_optional {
                assert!(
                    !doc.contains("Every field of the body is required"),
                    "{}: `{body_type}` has optional members, yet the doc says every field is required",
                    path.display()
                );
            }
            checked += 1;
        }
    }
    assert!(checked >= 8, "every replace operation was read ({checked})");
}

#[test]
fn parse_sp_metadata_is_documented_as_exactly_one_not_sparse() {
    let models = read("src/management/models.rs");
    let doc = doc_above(&models, "pub struct ParseSamlSpMetadata {");
    assert!(doc.contains("exactly one"), "{doc}");
    assert!(
        !doc.contains("sparse") && !doc.contains("left unchanged"),
        "an exactly-one body is not a sparse update: {doc}"
    );
}

#[test]
fn the_mtls_alias_type_names_seven_endpoints() {
    let discovery = read("src/oidc/discovery.rs");
    let doc = doc_above(&discovery, "pub struct MtlsEndpointAliases {");
    assert!(
        !doc.split(|c: char| !c.is_alphanumeric())
            .any(|w| w == "six"),
        "contract 1.58 added the seventh alias: {doc}"
    );
    assert!(doc.contains("seven"), "{doc}");
}
