// @generated by tools/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate
// with `tools/gen_management.py`; CI verifies the committed output is current.

//! Generated §27 surface conformance: every operation is reached once.
//!
//! Per operation: the SDK issues the registry's method against the registry's
//! path, and deserializes the response shape `openapi.json` declares. Semantics
//! that are not per-operation -- sparse-update key sets, secret redaction,
//! error mapping, pagination walks, the manifest -- are tested by hand in the
//! other `tests/management_*.rs` files.

#![cfg(feature = "rest")]

mod management_support;

use axiam_sdk::Sensitive;
use axiam_sdk::management::PageRequest;
use axiam_sdk::management::models;
use axiam_sdk::management::ops::*;
use uuid::Uuid;
use wiremock::MockServer;

use management_support::{
    EXAMPLE_ID, ORG_ID, TENANT_ID, expected_surface, logged_in_client, mount,
};

fn example_id() -> Uuid {
    Uuid::parse_str(EXAMPLE_ID).expect("fixture id parses")
}

/// Every operation this file exercises, in registry order.
///
/// §27.9: assert the count and the names, so a partial regeneration fails
/// here instead of quietly shipping 140 of 146.
const EXERCISED: [&str; 146] = [
    "organizations.list",
    "organizations.get",
    "organizations.update",
    "tenants.list",
    "tenants.create",
    "tenants.get",
    "tenants.update",
    "tenants.delete",
    "users.list",
    "users.create",
    "users.get",
    "users.update",
    "users.delete",
    "users.list_mfa_methods",
    "users.delete_mfa_method",
    "users.reset_mfa",
    "users.unlock",
    "users.list_roles",
    "groups.list",
    "groups.create",
    "groups.get",
    "groups.update",
    "groups.delete",
    "groups.list_members",
    "groups.add_member",
    "groups.remove_member",
    "groups.list_roles",
    "roles.list",
    "roles.create",
    "roles.get",
    "roles.update",
    "roles.delete",
    "roles.list_users",
    "roles.assign_to_user",
    "roles.unassign_from_user",
    "roles.list_groups",
    "roles.assign_to_group",
    "roles.unassign_from_group",
    "roles.list_permissions",
    "roles.grant_permission",
    "roles.revoke_permission",
    "permissions.list",
    "permissions.create",
    "permissions.get",
    "permissions.update",
    "permissions.delete",
    "resources.list",
    "resources.create",
    "resources.get",
    "resources.update",
    "resources.delete",
    "resources.list_children",
    "resources.list_ancestors",
    "scopes.list",
    "scopes.create",
    "scopes.get",
    "scopes.update",
    "scopes.delete",
    "service_accounts.list",
    "service_accounts.create",
    "service_accounts.get",
    "service_accounts.update",
    "service_accounts.delete",
    "service_accounts.rotate_secret",
    "service_accounts.bind_certificate",
    "certificates.list",
    "certificates.generate",
    "certificates.get",
    "certificates.revoke",
    "ca_certificates.list",
    "ca_certificates.generate",
    "ca_certificates.import_ca",
    "ca_certificates.get",
    "ca_certificates.revoke",
    "ca_certificates.migrate_custody",
    "ca_certificates.set_mtls_trust_anchor",
    "ca_certificates.list_signing_cas",
    "ca_certificates.generate_signing_ca",
    "ca_certificates.sign_signing_ca_csr",
    "pgp_keys.list",
    "pgp_keys.generate",
    "pgp_keys.get",
    "pgp_keys.revoke",
    "pgp_keys.encrypt",
    "pgp_keys.sign_audit_batch",
    "webhooks.list",
    "webhooks.create",
    "webhooks.get",
    "webhooks.update",
    "webhooks.delete",
    "oauth2_clients.list",
    "oauth2_clients.create",
    "oauth2_clients.get",
    "oauth2_clients.update",
    "oauth2_clients.delete",
    "federation.list_configs",
    "federation.create_config",
    "federation.get_config",
    "federation.update_config",
    "federation.delete_config",
    "federation.list_user_links",
    "federation.delete_link",
    "federation.oidc_authorize",
    "federation.oidc_callback",
    "notification_rules.list",
    "notification_rules.create",
    "notification_rules.get",
    "notification_rules.update",
    "notification_rules.delete",
    "email_config.get_org",
    "email_config.set_org",
    "email_config.delete_org",
    "email_config.test_org",
    "email_config.get_tenant",
    "email_config.set_tenant",
    "email_config.delete_tenant",
    "email_config.test_tenant",
    "settings.get_org",
    "settings.set_org",
    "settings.get_effective",
    "settings.set_effective",
    "settings.get_tenant_override",
    "settings.set_tenant_override",
    "settings.delete_tenant_override",
    "scim_tokens.list",
    "scim_tokens.create",
    "scim_tokens.revoke",
    "reactors.list",
    "reactors.create",
    "reactors.get",
    "reactors.update",
    "reactors.delete",
    "reactors.list_events",
    "webauthn_policy.get",
    "webauthn_policy.set",
    "webauthn_policy.compliance_report",
    "audit.list",
    "audit.list_system",
    "privacy.request_export",
    "privacy.download_export",
    "privacy.request_delete",
    "privacy.cancel_delete",
    "platform.health",
    "platform.ready",
    "platform.mds_status",
    "platform.mds_refresh",
];

#[test]
fn generated_surface_matches_the_registry() {
    let mut expected = expected_surface();
    let mut exercised: Vec<String> = EXERCISED.iter().map(|s| (*s).to_string()).collect();
    expected.sort();
    exercised.sort();
    assert_eq!(
        exercised, expected,
        "the generated surface and management-registry.json disagree"
    );
}

/// Reaches every operation in the `organizations` namespace.
#[tokio::test]
async fn organizations_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // organizations.list
    mount(&server, "GET", "/api/v1/organizations", 200, r#"{"items": [{"created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "slug": "example", "updated_at": "2026-08-26T00:00:00Z"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .organizations()
        .list(PageRequest::first(50))
        .await
        .expect("organizations.list");
    client
        .organizations()
        .list_all(PageRequest::first(50))
        .await
        .expect("organizations.list auto-paging");

    // organizations.get
    mount(&server, "GET", &format!("/api/v1/organizations/{ORG_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "slug": "example", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .organizations()
        .get()
        .await
        .expect("organizations.get");

    // organizations.update
    mount(&server, "PUT", &format!("/api/v1/organizations/{ORG_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "slug": "example", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .organizations()
        .update(&models::UpdateOrganizationRequest::default())
        .await
        .expect("organizations.update");
}

/// Reaches every operation in the `tenants` namespace.
#[tokio::test]
async fn tenants_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // tenants.list
    mount(&server, "GET", &format!("/api/v1/organizations/{ORG_ID}/tenants"), 200, r#"{"items": [{"created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "organization_id": "11111111-1111-4111-8111-111111111111", "slug": "example", "status": "Active", "updated_at": "2026-08-26T00:00:00Z"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .tenants()
        .list(PageRequest::first(50))
        .await
        .expect("tenants.list");
    client
        .tenants()
        .list_all(PageRequest::first(50))
        .await
        .expect("tenants.list auto-paging");

    // tenants.create
    mount(&server, "POST", &format!("/api/v1/organizations/{ORG_ID}/tenants"), 201, r#"{"created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "organization_id": "11111111-1111-4111-8111-111111111111", "slug": "example", "status": "Active", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .tenants()
        .create(&models::CreateTenantRequest {
            metadata: None,
            name: "example".to_string(),
            slug: "example".to_string(),
        })
        .await
        .expect("tenants.create");

    // tenants.get
    mount(&server, "GET", &format!("/api/v1/organizations/{ORG_ID}/tenants/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "organization_id": "11111111-1111-4111-8111-111111111111", "slug": "example", "status": "Active", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .tenants()
        .get(example_id())
        .await
        .expect("tenants.get");

    // tenants.update
    mount(&server, "PUT", &format!("/api/v1/organizations/{ORG_ID}/tenants/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "organization_id": "11111111-1111-4111-8111-111111111111", "slug": "example", "status": "Active", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .tenants()
        .update(example_id(), &models::UpdateTenant::default())
        .await
        .expect("tenants.update");

    // tenants.delete
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/organizations/{ORG_ID}/tenants/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .tenants()
        .delete(example_id())
        .await
        .expect("tenants.delete");
}

/// Reaches every operation in the `users` namespace.
#[tokio::test]
async fn users_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // users.list
    mount(&server, "GET", "/api/v1/users", 200, r#"{"items": [{"created_at": "2026-08-26T00:00:00Z", "email": "example", "email_verified": true, "failed_login_attempts": 1, "id": "11111111-1111-4111-8111-111111111111", "is_locked": true, "metadata": {}, "mfa_enabled": true, "status": "Active", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z", "username": "example"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .users()
        .list(PageRequest::first(50))
        .await
        .expect("users.list");
    client
        .users()
        .list_all(PageRequest::first(50))
        .await
        .expect("users.list auto-paging");

    // users.create
    mount(&server, "POST", "/api/v1/users", 201, r#"{"created_at": "2026-08-26T00:00:00Z", "email": "example", "email_verified": true, "failed_login_attempts": 1, "id": "11111111-1111-4111-8111-111111111111", "is_locked": true, "metadata": {}, "mfa_enabled": true, "status": "Active", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z", "username": "example"}"#).await;
    client
        .users()
        .create(&models::CreateUserRequest {
            email: "example".to_string(),
            metadata: None,
            opaque: None,
            password: Sensitive::new("example".to_string()),
            username: "example".to_string(),
        })
        .await
        .expect("users.create");

    // users.get
    mount(&server, "GET", &format!("/api/v1/users/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "email": "example", "email_verified": true, "failed_login_attempts": 1, "id": "11111111-1111-4111-8111-111111111111", "is_locked": true, "metadata": {}, "mfa_enabled": true, "status": "Active", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z", "username": "example"}"#).await;
    client.users().get(example_id()).await.expect("users.get");

    // users.update
    mount(&server, "PUT", &format!("/api/v1/users/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "email": "example", "email_verified": true, "failed_login_attempts": 1, "id": "11111111-1111-4111-8111-111111111111", "is_locked": true, "metadata": {}, "mfa_enabled": true, "status": "Active", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z", "username": "example"}"#).await;
    client
        .users()
        .update(example_id(), &models::UpdateUserRequest::default())
        .await
        .expect("users.update");

    // users.delete
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/users/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .users()
        .delete(example_id())
        .await
        .expect("users.delete");

    // users.list_mfa_methods
    mount(&server, "GET", &format!("/api/v1/users/{EXAMPLE_ID}/mfa-methods"), 200, r#"[{"created_at": "example", "method_id": "example", "method_type": "Totp", "name": "example"}]"#).await;
    client
        .users()
        .list_mfa_methods(example_id())
        .await
        .expect("users.list_mfa_methods");

    // users.delete_mfa_method
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/users/{EXAMPLE_ID}/mfa-methods/example"),
        204,
        "",
    )
    .await;
    client
        .users()
        .delete_mfa_method(example_id(), "example")
        .await
        .expect("users.delete_mfa_method");

    // users.reset_mfa
    mount(
        &server,
        "POST",
        &format!("/api/v1/users/{EXAMPLE_ID}/reset-mfa"),
        204,
        "",
    )
    .await;
    client
        .users()
        .reset_mfa(example_id())
        .await
        .expect("users.reset_mfa");

    // users.unlock
    mount(&server, "POST", &format!("/api/v1/users/{EXAMPLE_ID}/unlock"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "email": "example", "email_verified": true, "failed_login_attempts": 1, "id": "11111111-1111-4111-8111-111111111111", "is_locked": true, "metadata": {}, "mfa_enabled": true, "status": "Active", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z", "username": "example"}"#).await;
    client
        .users()
        .unlock(example_id())
        .await
        .expect("users.unlock");

    // users.list_roles
    mount(&server, "GET", &format!("/api/v1/users/{EXAMPLE_ID}/roles"), 200, r#"[{"role": {"created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "is_global": true, "name": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}}]"#).await;
    client
        .users()
        .list_roles(example_id())
        .await
        .expect("users.list_roles");
}

/// Reaches every operation in the `groups` namespace.
#[tokio::test]
async fn groups_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // groups.list
    mount(&server, "GET", "/api/v1/groups", 200, r#"{"items": [{"created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .groups()
        .list(PageRequest::first(50))
        .await
        .expect("groups.list");
    client
        .groups()
        .list_all(PageRequest::first(50))
        .await
        .expect("groups.list auto-paging");

    // groups.create
    mount(&server, "POST", "/api/v1/groups", 201, r#"{"created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .groups()
        .create(&models::CreateGroupRequest {
            description: "example".to_string(),
            metadata: None,
            name: "example".to_string(),
        })
        .await
        .expect("groups.create");

    // groups.get
    mount(&server, "GET", &format!("/api/v1/groups/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client.groups().get(example_id()).await.expect("groups.get");

    // groups.update
    mount(&server, "PUT", &format!("/api/v1/groups/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .groups()
        .update(example_id(), &models::UpdateGroup::default())
        .await
        .expect("groups.update");

    // groups.delete
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/groups/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .groups()
        .delete(example_id())
        .await
        .expect("groups.delete");

    // groups.list_members
    mount(&server, "GET", &format!("/api/v1/groups/{EXAMPLE_ID}/members"), 200, r#"{"items": [{"created_at": "2026-08-26T00:00:00Z", "email": "example", "email_verified": true, "failed_login_attempts": 1, "id": "11111111-1111-4111-8111-111111111111", "is_locked": true, "metadata": {}, "mfa_enabled": true, "status": "Active", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z", "username": "example"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .groups()
        .list_members(example_id(), PageRequest::first(50))
        .await
        .expect("groups.list_members");
    client
        .groups()
        .list_members_all(example_id(), PageRequest::first(50))
        .await
        .expect("groups.list_members auto-paging");

    // groups.add_member
    mount(
        &server,
        "POST",
        &format!("/api/v1/groups/{EXAMPLE_ID}/members"),
        204,
        "",
    )
    .await;
    client
        .groups()
        .add_member(
            example_id(),
            &models::AddMemberRequest {
                user_id: example_id(),
            },
        )
        .await
        .expect("groups.add_member");

    // groups.remove_member
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/groups/{EXAMPLE_ID}/members/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .groups()
        .remove_member(example_id(), example_id())
        .await
        .expect("groups.remove_member");

    // groups.list_roles
    mount(&server, "GET", &format!("/api/v1/groups/{EXAMPLE_ID}/roles"), 200, r#"[{"role": {"created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "is_global": true, "name": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}}]"#).await;
    client
        .groups()
        .list_roles(example_id())
        .await
        .expect("groups.list_roles");
}

/// Reaches every operation in the `roles` namespace.
#[tokio::test]
async fn roles_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // roles.list
    mount(&server, "GET", "/api/v1/roles", 200, r#"{"items": [{"created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "is_global": true, "name": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .roles()
        .list(PageRequest::first(50))
        .await
        .expect("roles.list");
    client
        .roles()
        .list_all(PageRequest::first(50))
        .await
        .expect("roles.list auto-paging");

    // roles.create
    mount(&server, "POST", "/api/v1/roles", 201, r#"{"created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "is_global": true, "name": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .roles()
        .create(&models::CreateRoleRequest {
            description: "example".to_string(),
            is_global: true,
            name: "example".to_string(),
        })
        .await
        .expect("roles.create");

    // roles.get
    mount(&server, "GET", &format!("/api/v1/roles/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "is_global": true, "name": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client.roles().get(example_id()).await.expect("roles.get");

    // roles.update
    mount(&server, "PUT", &format!("/api/v1/roles/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "is_global": true, "name": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .roles()
        .update(example_id(), &models::UpdateRole::default())
        .await
        .expect("roles.update");

    // roles.delete
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/roles/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .roles()
        .delete(example_id())
        .await
        .expect("roles.delete");

    // roles.list_users
    mount(&server, "GET", &format!("/api/v1/roles/{EXAMPLE_ID}/users"), 200, r#"[{"user": {"created_at": "2026-08-26T00:00:00Z", "email": "example", "email_verified": true, "failed_login_attempts": 1, "id": "11111111-1111-4111-8111-111111111111", "is_locked": true, "metadata": {}, "mfa_enabled": true, "status": "Active", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z", "username": "example"}}]"#).await;
    client
        .roles()
        .list_users(example_id())
        .await
        .expect("roles.list_users");

    // roles.assign_to_user
    mount(
        &server,
        "POST",
        &format!("/api/v1/roles/{EXAMPLE_ID}/users"),
        204,
        "",
    )
    .await;
    client
        .roles()
        .assign_to_user(
            example_id(),
            &models::AssignRoleToUserRequest {
                resource_id: None,
                user_id: example_id(),
            },
        )
        .await
        .expect("roles.assign_to_user");

    // roles.unassign_from_user
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/roles/{EXAMPLE_ID}/users/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .roles()
        .unassign_from_user(example_id(), example_id(), None)
        .await
        .expect("roles.unassign_from_user");

    // roles.list_groups
    mount(&server, "GET", &format!("/api/v1/roles/{EXAMPLE_ID}/groups"), 200, r#"[{"group": {"created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}}]"#).await;
    client
        .roles()
        .list_groups(example_id())
        .await
        .expect("roles.list_groups");

    // roles.assign_to_group
    mount(
        &server,
        "POST",
        &format!("/api/v1/roles/{EXAMPLE_ID}/groups"),
        204,
        "",
    )
    .await;
    client
        .roles()
        .assign_to_group(
            example_id(),
            &models::AssignRoleToGroupRequest {
                group_id: example_id(),
                resource_id: None,
            },
        )
        .await
        .expect("roles.assign_to_group");

    // roles.unassign_from_group
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/roles/{EXAMPLE_ID}/groups/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .roles()
        .unassign_from_group(example_id(), example_id(), None)
        .await
        .expect("roles.unassign_from_group");

    // roles.list_permissions
    mount(&server, "GET", &format!("/api/v1/roles/{EXAMPLE_ID}/permissions"), 200, r#"[{"effect": "allow", "permission": {"action": "example", "created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}, "scope_ids": [], "scopes": []}]"#).await;
    client
        .roles()
        .list_permissions(example_id())
        .await
        .expect("roles.list_permissions");

    // roles.grant_permission
    mount(
        &server,
        "POST",
        &format!("/api/v1/roles/{EXAMPLE_ID}/permissions"),
        204,
        "",
    )
    .await;
    client
        .roles()
        .grant_permission(
            example_id(),
            &models::GrantPermissionRequest {
                effect: None,
                permission_id: example_id(),
                scope_ids: None,
            },
        )
        .await
        .expect("roles.grant_permission");

    // roles.revoke_permission
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/roles/{EXAMPLE_ID}/permissions/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .roles()
        .revoke_permission(example_id(), example_id())
        .await
        .expect("roles.revoke_permission");
}

/// Reaches every operation in the `permissions` namespace.
#[tokio::test]
async fn permissions_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // permissions.list
    mount(&server, "GET", "/api/v1/permissions", 200, r#"{"items": [{"action": "example", "created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .permissions()
        .list(PageRequest::first(50))
        .await
        .expect("permissions.list");
    client
        .permissions()
        .list_all(PageRequest::first(50))
        .await
        .expect("permissions.list auto-paging");

    // permissions.create
    mount(&server, "POST", "/api/v1/permissions", 201, r#"{"action": "example", "created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .permissions()
        .create(&models::CreatePermissionRequest {
            action: "example".to_string(),
            description: "example".to_string(),
        })
        .await
        .expect("permissions.create");

    // permissions.get
    mount(&server, "GET", &format!("/api/v1/permissions/{EXAMPLE_ID}"), 200, r#"{"action": "example", "created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .permissions()
        .get(example_id())
        .await
        .expect("permissions.get");

    // permissions.update
    mount(&server, "PUT", &format!("/api/v1/permissions/{EXAMPLE_ID}"), 200, r#"{"action": "example", "created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .permissions()
        .update(example_id(), &models::UpdatePermissionRequest::default())
        .await
        .expect("permissions.update");

    // permissions.delete
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/permissions/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .permissions()
        .delete(example_id())
        .await
        .expect("permissions.delete");
}

/// Reaches every operation in the `resources` namespace.
#[tokio::test]
async fn resources_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // resources.list
    mount(&server, "GET", "/api/v1/resources", 200, r#"{"items": [{"created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "resource_type": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .resources()
        .list(PageRequest::first(50))
        .await
        .expect("resources.list");
    client
        .resources()
        .list_all(PageRequest::first(50))
        .await
        .expect("resources.list auto-paging");

    // resources.create
    mount(&server, "POST", "/api/v1/resources", 201, r#"{"created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "resource_type": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .resources()
        .create(&models::CreateResourceRequest {
            metadata: None,
            name: "example".to_string(),
            parent_id: None,
            resource_type: "example".to_string(),
        })
        .await
        .expect("resources.create");

    // resources.get
    mount(&server, "GET", &format!("/api/v1/resources/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "resource_type": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .resources()
        .get(example_id())
        .await
        .expect("resources.get");

    // resources.update
    mount(&server, "PUT", &format!("/api/v1/resources/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "resource_type": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .resources()
        .update(example_id(), &models::UpdateResourceRequest::default())
        .await
        .expect("resources.update");

    // resources.delete
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/resources/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .resources()
        .delete(example_id())
        .await
        .expect("resources.delete");

    // resources.list_children
    mount(&server, "GET", &format!("/api/v1/resources/{EXAMPLE_ID}/children"), 200, r#"[{"created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "resource_type": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}]"#).await;
    client
        .resources()
        .list_children(example_id())
        .await
        .expect("resources.list_children");

    // resources.list_ancestors
    mount(&server, "GET", &format!("/api/v1/resources/{EXAMPLE_ID}/ancestors"), 200, r#"[{"created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "name": "example", "resource_type": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}]"#).await;
    client
        .resources()
        .list_ancestors(example_id())
        .await
        .expect("resources.list_ancestors");
}

/// Reaches every operation in the `scopes` namespace.
#[tokio::test]
async fn scopes_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // scopes.list
    mount(&server, "GET", &format!("/api/v1/resources/{EXAMPLE_ID}/scopes"), 200, r#"[{"created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "name": "example", "resource_id": "11111111-1111-4111-8111-111111111111", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}]"#).await;
    client
        .scopes()
        .list(example_id())
        .await
        .expect("scopes.list");

    // scopes.create
    mount(&server, "POST", &format!("/api/v1/resources/{EXAMPLE_ID}/scopes"), 201, r#"{"created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "name": "example", "resource_id": "11111111-1111-4111-8111-111111111111", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .scopes()
        .create(
            example_id(),
            &models::CreateScopeRequest {
                description: "example".to_string(),
                name: "example".to_string(),
            },
        )
        .await
        .expect("scopes.create");

    // scopes.get
    mount(&server, "GET", &format!("/api/v1/resources/{EXAMPLE_ID}/scopes/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "name": "example", "resource_id": "11111111-1111-4111-8111-111111111111", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .scopes()
        .get(example_id(), example_id())
        .await
        .expect("scopes.get");

    // scopes.update
    mount(&server, "PUT", &format!("/api/v1/resources/{EXAMPLE_ID}/scopes/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "description": "example", "id": "11111111-1111-4111-8111-111111111111", "name": "example", "resource_id": "11111111-1111-4111-8111-111111111111", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .scopes()
        .update(
            example_id(),
            example_id(),
            &models::UpdateScopeRequest::default(),
        )
        .await
        .expect("scopes.update");

    // scopes.delete
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/resources/{EXAMPLE_ID}/scopes/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .scopes()
        .delete(example_id(), example_id())
        .await
        .expect("scopes.delete");
}

/// Reaches every operation in the `service_accounts` namespace.
#[tokio::test]
async fn service_accounts_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // service_accounts.list
    mount(&server, "GET", "/api/v1/service-accounts", 200, r#"{"items": [{"client_id": "example", "created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "name": "example", "status": "Active", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .service_accounts()
        .list(PageRequest::first(50))
        .await
        .expect("service_accounts.list");
    client
        .service_accounts()
        .list_all(PageRequest::first(50))
        .await
        .expect("service_accounts.list auto-paging");

    // service_accounts.create
    mount(&server, "POST", "/api/v1/service-accounts", 201, r#"{"client_id": "example", "client_secret": "example", "created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "name": "example", "status": "Active", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .service_accounts()
        .create(&models::CreateServiceAccountRequest {
            description: None,
            name: "example".to_string(),
        })
        .await
        .expect("service_accounts.create");

    // service_accounts.get
    mount(&server, "GET", &format!("/api/v1/service-accounts/{EXAMPLE_ID}"), 200, r#"{"client_id": "example", "created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "name": "example", "status": "Active", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .service_accounts()
        .get(example_id())
        .await
        .expect("service_accounts.get");

    // service_accounts.update
    mount(&server, "PUT", &format!("/api/v1/service-accounts/{EXAMPLE_ID}"), 200, r#"{"client_id": "example", "created_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "name": "example", "status": "Active", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .service_accounts()
        .update(example_id(), &models::UpdateServiceAccount::default())
        .await
        .expect("service_accounts.update");

    // service_accounts.delete
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/service-accounts/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .service_accounts()
        .delete(example_id())
        .await
        .expect("service_accounts.delete");

    // service_accounts.rotate_secret
    mount(
        &server,
        "POST",
        &format!("/api/v1/service-accounts/{EXAMPLE_ID}/rotate-secret"),
        200,
        r#"{"client_secret": "example"}"#,
    )
    .await;
    client
        .service_accounts()
        .rotate_secret(example_id())
        .await
        .expect("service_accounts.rotate_secret");

    // service_accounts.bind_certificate
    mount(
        &server,
        "POST",
        &format!("/api/v1/service-accounts/{EXAMPLE_ID}/bind-certificate"),
        200,
        "",
    )
    .await;
    client
        .service_accounts()
        .bind_certificate(
            example_id(),
            &models::BindCertificate {
                certificate_id: example_id(),
            },
        )
        .await
        .expect("service_accounts.bind_certificate");
}

/// Reaches every operation in the `certificates` namespace.
#[tokio::test]
async fn certificates_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // certificates.list
    mount(&server, "GET", "/api/v1/certificates", 200, r#"{"items": [{"cert_type": "User", "created_at": "2026-08-26T00:00:00Z", "fingerprint": "example", "id": "11111111-1111-4111-8111-111111111111", "issuer_ca_id": "11111111-1111-4111-8111-111111111111", "key_algorithm": "Rsa4096", "metadata": {}, "not_after": "2026-08-26T00:00:00Z", "not_before": "2026-08-26T00:00:00Z", "public_cert_pem": "example", "status": "Active", "subject": "example", "tenant_id": "11111111-1111-4111-8111-111111111111"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .certificates()
        .list(PageRequest::first(50))
        .await
        .expect("certificates.list");
    client
        .certificates()
        .list_all(PageRequest::first(50))
        .await
        .expect("certificates.list auto-paging");

    // certificates.generate
    mount(&server, "POST", "/api/v1/certificates", 201, r#"{"cert_type": "User", "created_at": "2026-08-26T00:00:00Z", "fingerprint": "example", "id": "11111111-1111-4111-8111-111111111111", "issuer_ca_id": "11111111-1111-4111-8111-111111111111", "key_algorithm": "Rsa4096", "metadata": {}, "not_after": "2026-08-26T00:00:00Z", "not_before": "2026-08-26T00:00:00Z", "public_cert_pem": "example", "status": "Active", "subject": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "private_key_pem": "example"}"#).await;
    client
        .certificates()
        .generate(&models::CreateCertificateRequest {
            cert_type: models::CertificateType::User,
            issuer_ca_id: example_id(),
            key_algorithm: models::KeyAlgorithm::Rsa4096,
            metadata: None,
            subject: "example".to_string(),
            validity_days: 1,
        })
        .await
        .expect("certificates.generate");

    // certificates.get
    mount(&server, "GET", &format!("/api/v1/certificates/{EXAMPLE_ID}"), 200, r#"{"cert_type": "User", "created_at": "2026-08-26T00:00:00Z", "fingerprint": "example", "id": "11111111-1111-4111-8111-111111111111", "issuer_ca_id": "11111111-1111-4111-8111-111111111111", "key_algorithm": "Rsa4096", "metadata": {}, "not_after": "2026-08-26T00:00:00Z", "not_before": "2026-08-26T00:00:00Z", "public_cert_pem": "example", "status": "Active", "subject": "example", "tenant_id": "11111111-1111-4111-8111-111111111111"}"#).await;
    client
        .certificates()
        .get(example_id())
        .await
        .expect("certificates.get");

    // certificates.revoke
    mount(
        &server,
        "POST",
        &format!("/api/v1/certificates/{EXAMPLE_ID}/revoke"),
        200,
        "",
    )
    .await;
    client
        .certificates()
        .revoke(example_id())
        .await
        .expect("certificates.revoke");
}

/// Reaches every operation in the `ca_certificates` namespace.
#[tokio::test]
async fn ca_certificates_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // ca_certificates.list
    mount(&server, "GET", &format!("/api/v1/organizations/{ORG_ID}/ca-certificates"), 200, r#"{"items": [{"created_at": "2026-08-26T00:00:00Z", "fingerprint": "example", "id": "11111111-1111-4111-8111-111111111111", "key_algorithm": "Rsa4096", "not_after": "2026-08-26T00:00:00Z", "not_before": "2026-08-26T00:00:00Z", "organization_id": "11111111-1111-4111-8111-111111111111", "public_cert_pem": "example", "status": "Active", "subject": "example"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .ca_certificates()
        .list(PageRequest::first(50))
        .await
        .expect("ca_certificates.list");
    client
        .ca_certificates()
        .list_all(PageRequest::first(50))
        .await
        .expect("ca_certificates.list auto-paging");

    // ca_certificates.generate
    mount(&server, "POST", &format!("/api/v1/organizations/{ORG_ID}/ca-certificates"), 201, r#"{"created_at": "2026-08-26T00:00:00Z", "fingerprint": "example", "id": "11111111-1111-4111-8111-111111111111", "key_algorithm": "Rsa4096", "not_after": "2026-08-26T00:00:00Z", "not_before": "2026-08-26T00:00:00Z", "organization_id": "11111111-1111-4111-8111-111111111111", "public_cert_pem": "example", "status": "Active", "subject": "example"}"#).await;
    client
        .ca_certificates()
        .generate(&models::CreateCaCertificateRequest {
            intermediate_subject: None,
            intermediate_validity_days: None,
            issue_from_root: None,
            key_algorithm: models::KeyAlgorithm::Rsa4096,
            subject: "example".to_string(),
            validity_days: 1,
        })
        .await
        .expect("ca_certificates.generate");

    // ca_certificates.import_ca
    mount(&server, "POST", &format!("/api/v1/organizations/{ORG_ID}/ca-certificates/import"), 201, r#"{"created_at": "2026-08-26T00:00:00Z", "fingerprint": "example", "id": "11111111-1111-4111-8111-111111111111", "key_algorithm": "Rsa4096", "not_after": "2026-08-26T00:00:00Z", "not_before": "2026-08-26T00:00:00Z", "organization_id": "11111111-1111-4111-8111-111111111111", "public_cert_pem": "example", "status": "Active", "subject": "example"}"#).await;
    client
        .ca_certificates()
        .import_ca(&models::ImportCaCertificateRequest {
            private_key_pem: None,
            public_cert_pem: "example".to_string(),
        })
        .await
        .expect("ca_certificates.import_ca");

    // ca_certificates.get
    mount(&server, "GET", &format!("/api/v1/organizations/{ORG_ID}/ca-certificates/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "fingerprint": "example", "id": "11111111-1111-4111-8111-111111111111", "key_algorithm": "Rsa4096", "not_after": "2026-08-26T00:00:00Z", "not_before": "2026-08-26T00:00:00Z", "organization_id": "11111111-1111-4111-8111-111111111111", "public_cert_pem": "example", "status": "Active", "subject": "example"}"#).await;
    client
        .ca_certificates()
        .get(example_id())
        .await
        .expect("ca_certificates.get");

    // ca_certificates.revoke
    mount(
        &server,
        "POST",
        &format!("/api/v1/organizations/{ORG_ID}/ca-certificates/{EXAMPLE_ID}/revoke"),
        200,
        "",
    )
    .await;
    client
        .ca_certificates()
        .revoke(example_id())
        .await
        .expect("ca_certificates.revoke");

    // ca_certificates.migrate_custody
    mount(&server, "POST", &format!("/api/v1/organizations/{ORG_ID}/ca-certificates/{EXAMPLE_ID}/migrate-custody"), 200, r#"{"ca_certificate_id": "11111111-1111-4111-8111-111111111111", "key_custody": "example", "previous_custody": "example"}"#).await;
    client
        .ca_certificates()
        .migrate_custody(example_id())
        .await
        .expect("ca_certificates.migrate_custody");

    // ca_certificates.set_mtls_trust_anchor
    mount(&server, "PUT", &format!("/api/v1/organizations/{ORG_ID}/ca-certificates/{EXAMPLE_ID}/mtls-trust-anchor"), 200, r#"{"ca_certificate_id": "11111111-1111-4111-8111-111111111111", "message": "example", "mtls_trust_anchor": true, "restart_required": true}"#).await;
    client
        .ca_certificates()
        .set_mtls_trust_anchor(example_id(), &models::SetMtlsTrustAnchor { enabled: true })
        .await
        .expect("ca_certificates.set_mtls_trust_anchor");

    // ca_certificates.list_signing_cas
    mount(&server, "GET", &format!("/api/v1/organizations/{ORG_ID}/tenants/{EXAMPLE_ID}/signing-cas"), 200, r#"{"items": [{"created_at": "2026-08-26T00:00:00Z", "fingerprint": "example", "id": "11111111-1111-4111-8111-111111111111", "key_algorithm": "Rsa4096", "not_after": "2026-08-26T00:00:00Z", "not_before": "2026-08-26T00:00:00Z", "organization_id": "11111111-1111-4111-8111-111111111111", "public_cert_pem": "example", "status": "Active", "subject": "example"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .ca_certificates()
        .list_signing_cas(example_id(), PageRequest::first(50))
        .await
        .expect("ca_certificates.list_signing_cas");
    client
        .ca_certificates()
        .list_signing_cas_all(example_id(), PageRequest::first(50))
        .await
        .expect("ca_certificates.list_signing_cas auto-paging");

    // ca_certificates.generate_signing_ca
    mount(&server, "POST", &format!("/api/v1/organizations/{ORG_ID}/tenants/{EXAMPLE_ID}/signing-cas"), 201, r#"{"created_at": "2026-08-26T00:00:00Z", "fingerprint": "example", "id": "11111111-1111-4111-8111-111111111111", "key_algorithm": "Rsa4096", "not_after": "2026-08-26T00:00:00Z", "not_before": "2026-08-26T00:00:00Z", "organization_id": "11111111-1111-4111-8111-111111111111", "public_cert_pem": "example", "status": "Active", "subject": "example"}"#).await;
    client
        .ca_certificates()
        .generate_signing_ca(
            example_id(),
            &models::CreateIntermediateCaRequest {
                key_algorithm: models::KeyAlgorithm::Rsa4096,
                parent_ca_id: example_id(),
                subject: "example".to_string(),
                validity_days: 1,
            },
        )
        .await
        .expect("ca_certificates.generate_signing_ca");

    // ca_certificates.sign_signing_ca_csr
    mount(&server, "POST", &format!("/api/v1/organizations/{ORG_ID}/tenants/{EXAMPLE_ID}/signing-cas/sign-csr"), 201, r#"{"created_at": "2026-08-26T00:00:00Z", "fingerprint": "example", "id": "11111111-1111-4111-8111-111111111111", "key_algorithm": "Rsa4096", "not_after": "2026-08-26T00:00:00Z", "not_before": "2026-08-26T00:00:00Z", "organization_id": "11111111-1111-4111-8111-111111111111", "public_cert_pem": "example", "status": "Active", "subject": "example"}"#).await;
    client
        .ca_certificates()
        .sign_signing_ca_csr(
            example_id(),
            &models::SignIntermediateCsrRequest {
                csr_pem: "example".to_string(),
                parent_ca_id: example_id(),
                validity_days: 1,
            },
        )
        .await
        .expect("ca_certificates.sign_signing_ca_csr");
}

/// Reaches every operation in the `pgp_keys` namespace.
#[tokio::test]
async fn pgp_keys_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // pgp_keys.list
    mount(&server, "GET", "/api/v1/pgp-keys", 200, r#"{"items": [{"algorithm": "Rsa4096", "created_at": "2026-08-26T00:00:00Z", "fingerprint": "example", "id": "11111111-1111-4111-8111-111111111111", "name": "example", "public_key_armored": "example", "purpose": "AuditSigning", "status": "Active", "tenant_id": "11111111-1111-4111-8111-111111111111"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .pgp_keys()
        .list(PageRequest::first(50))
        .await
        .expect("pgp_keys.list");
    client
        .pgp_keys()
        .list_all(PageRequest::first(50))
        .await
        .expect("pgp_keys.list auto-paging");

    // pgp_keys.generate
    mount(&server, "POST", "/api/v1/pgp-keys", 201, r#"{"algorithm": "Rsa4096", "created_at": "2026-08-26T00:00:00Z", "fingerprint": "example", "id": "11111111-1111-4111-8111-111111111111", "name": "example", "public_key_armored": "example", "purpose": "AuditSigning", "status": "Active", "tenant_id": "11111111-1111-4111-8111-111111111111"}"#).await;
    client
        .pgp_keys()
        .generate(&models::CreatePgpKeyRequest {
            algorithm: models::PgpKeyAlgorithm::Rsa4096,
            email: "example".to_string(),
            name: "example".to_string(),
            purpose: models::PgpKeyPurpose::AuditSigning,
        })
        .await
        .expect("pgp_keys.generate");

    // pgp_keys.get
    mount(&server, "GET", &format!("/api/v1/pgp-keys/{EXAMPLE_ID}"), 200, r#"{"algorithm": "Rsa4096", "created_at": "2026-08-26T00:00:00Z", "fingerprint": "example", "id": "11111111-1111-4111-8111-111111111111", "name": "example", "public_key_armored": "example", "purpose": "AuditSigning", "status": "Active", "tenant_id": "11111111-1111-4111-8111-111111111111"}"#).await;
    client
        .pgp_keys()
        .get(example_id())
        .await
        .expect("pgp_keys.get");

    // pgp_keys.revoke
    mount(
        &server,
        "POST",
        &format!("/api/v1/pgp-keys/{EXAMPLE_ID}/revoke"),
        200,
        "",
    )
    .await;
    client
        .pgp_keys()
        .revoke(example_id())
        .await
        .expect("pgp_keys.revoke");

    // pgp_keys.encrypt
    mount(&server, "POST", &format!("/api/v1/pgp-keys/{EXAMPLE_ID}/encrypt"), 200, r#"{"ciphertext_armored": "example", "recipient_key_id": "11111111-1111-4111-8111-111111111111"}"#).await;
    client
        .pgp_keys()
        .encrypt(
            example_id(),
            &models::EncryptRequest {
                data_base64: "example".to_string(),
            },
        )
        .await
        .expect("pgp_keys.encrypt");

    // pgp_keys.sign_audit_batch
    mount(&server, "POST", "/api/v1/pgp-keys/sign-audit-batch", 200, r#"{"batch_id": "11111111-1111-4111-8111-111111111111", "entry_ids": [], "signature_armored": "example", "signed_at": "2026-08-26T00:00:00Z", "signing_key_id": "11111111-1111-4111-8111-111111111111", "tenant_id": "11111111-1111-4111-8111-111111111111"}"#).await;
    client
        .pgp_keys()
        .sign_audit_batch(&models::SignAuditBatchRequest {
            entry_ids: Vec::new(),
        })
        .await
        .expect("pgp_keys.sign_audit_batch");
}

/// Reaches every operation in the `webhooks` namespace.
#[tokio::test]
async fn webhooks_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // webhooks.list
    mount(&server, "GET", "/api/v1/webhooks", 200, r#"{"items": [{"created_at": "2026-08-26T00:00:00Z", "enabled": true, "events": [], "id": "11111111-1111-4111-8111-111111111111", "retry_policy": {"backoff_multiplier": 1.0, "initial_delay_secs": 1, "max_retries": 1}, "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z", "url": "example"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .webhooks()
        .list(PageRequest::first(50))
        .await
        .expect("webhooks.list");
    client
        .webhooks()
        .list_all(PageRequest::first(50))
        .await
        .expect("webhooks.list auto-paging");

    // webhooks.create
    mount(&server, "POST", "/api/v1/webhooks", 201, r#"{"created_at": "2026-08-26T00:00:00Z", "enabled": true, "events": [], "id": "11111111-1111-4111-8111-111111111111", "retry_policy": {"backoff_multiplier": 1.0, "initial_delay_secs": 1, "max_retries": 1}, "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z", "url": "example"}"#).await;
    client
        .webhooks()
        .create(&models::CreateWebhookRequest {
            events: Vec::new(),
            retry_policy: None,
            secret: Sensitive::new("example".to_string()),
            url: "example".to_string(),
        })
        .await
        .expect("webhooks.create");

    // webhooks.get
    mount(&server, "GET", &format!("/api/v1/webhooks/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "enabled": true, "events": [], "id": "11111111-1111-4111-8111-111111111111", "retry_policy": {"backoff_multiplier": 1.0, "initial_delay_secs": 1, "max_retries": 1}, "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z", "url": "example"}"#).await;
    client
        .webhooks()
        .get(example_id())
        .await
        .expect("webhooks.get");

    // webhooks.update
    mount(&server, "PUT", &format!("/api/v1/webhooks/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "enabled": true, "events": [], "id": "11111111-1111-4111-8111-111111111111", "retry_policy": {"backoff_multiplier": 1.0, "initial_delay_secs": 1, "max_retries": 1}, "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z", "url": "example"}"#).await;
    client
        .webhooks()
        .update(example_id(), &models::UpdateWebhookRequest::default())
        .await
        .expect("webhooks.update");

    // webhooks.delete
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/webhooks/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .webhooks()
        .delete(example_id())
        .await
        .expect("webhooks.delete");
}

/// Reaches every operation in the `oauth2_clients` namespace.
#[tokio::test]
async fn oauth2_clients_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // oauth2_clients.list
    mount(&server, "GET", "/api/v1/oauth2-clients", 200, r#"{"items": [{"client_id": "example", "created_at": "2026-08-26T00:00:00Z", "dpop_bound_access_tokens": true, "dpop_require_nonce": true, "grant_types": [], "id": "11111111-1111-4111-8111-111111111111", "name": "example", "profile": "standard", "redirect_uris": [], "require_par": true, "scopes": [], "self_signed_tls_client_auth_thumbprints": [], "tenant_id": "11111111-1111-4111-8111-111111111111", "tls_client_certificate_bound_access_tokens": true, "token_endpoint_auth_method": "client_secret_post", "updated_at": "2026-08-26T00:00:00Z"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .oauth2_clients()
        .list(PageRequest::first(50))
        .await
        .expect("oauth2_clients.list");
    client
        .oauth2_clients()
        .list_all(PageRequest::first(50))
        .await
        .expect("oauth2_clients.list auto-paging");

    // oauth2_clients.create
    mount(&server, "POST", "/api/v1/oauth2-clients", 201, r#"{"client_id": "example", "client_secret": "example", "created_at": "2026-08-26T00:00:00Z", "grant_types": [], "id": "11111111-1111-4111-8111-111111111111", "name": "example", "redirect_uris": [], "scopes": [], "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .oauth2_clients()
        .create(&models::CreateOAuth2ClientRequest {
            backchannel_logout_uri: None,
            dpop_bound_access_tokens: None,
            dpop_require_nonce: None,
            grant_types: Vec::new(),
            jwks: None,
            jwks_uri: None,
            name: "example".to_string(),
            post_logout_redirect_uris: None,
            profile: None,
            redirect_uris: Vec::new(),
            require_par: None,
            scopes: Vec::new(),
            self_signed_tls_client_auth_thumbprints: None,
            tls_client_auth_san_dns: None,
            tls_client_auth_san_uri: None,
            tls_client_auth_subject_dn: None,
            tls_client_certificate_bound_access_tokens: None,
            token_endpoint_auth_method: None,
        })
        .await
        .expect("oauth2_clients.create");

    // oauth2_clients.get
    mount(&server, "GET", &format!("/api/v1/oauth2-clients/{EXAMPLE_ID}"), 200, r#"{"client_id": "example", "created_at": "2026-08-26T00:00:00Z", "dpop_bound_access_tokens": true, "dpop_require_nonce": true, "grant_types": [], "id": "11111111-1111-4111-8111-111111111111", "name": "example", "profile": "standard", "redirect_uris": [], "require_par": true, "scopes": [], "self_signed_tls_client_auth_thumbprints": [], "tenant_id": "11111111-1111-4111-8111-111111111111", "tls_client_certificate_bound_access_tokens": true, "token_endpoint_auth_method": "client_secret_post", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .oauth2_clients()
        .get(example_id())
        .await
        .expect("oauth2_clients.get");

    // oauth2_clients.update
    mount(&server, "PUT", &format!("/api/v1/oauth2-clients/{EXAMPLE_ID}"), 200, r#"{"client_id": "example", "created_at": "2026-08-26T00:00:00Z", "dpop_bound_access_tokens": true, "dpop_require_nonce": true, "grant_types": [], "id": "11111111-1111-4111-8111-111111111111", "name": "example", "profile": "standard", "redirect_uris": [], "require_par": true, "scopes": [], "self_signed_tls_client_auth_thumbprints": [], "tenant_id": "11111111-1111-4111-8111-111111111111", "tls_client_certificate_bound_access_tokens": true, "token_endpoint_auth_method": "client_secret_post", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .oauth2_clients()
        .update(example_id(), &models::UpdateOAuth2ClientRequest::default())
        .await
        .expect("oauth2_clients.update");

    // oauth2_clients.delete
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/oauth2-clients/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .oauth2_clients()
        .delete(example_id())
        .await
        .expect("oauth2_clients.delete");
}

/// Reaches every operation in the `federation` namespace.
#[tokio::test]
async fn federation_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // federation.list_configs
    mount(&server, "GET", "/api/v1/federation-configs", 200, r#"{"items": [{"attribute_map": {}, "client_id": "example", "created_at": "2026-08-26T00:00:00Z", "enabled": true, "id": "11111111-1111-4111-8111-111111111111", "protocol": "example", "provider": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "token_exchange": {"accepted_audiences": [], "enabled": true, "max_token_age_secs": 1, "scope_map": {}, "subject_mapping": "example"}, "updated_at": "2026-08-26T00:00:00Z"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .federation()
        .list_configs(PageRequest::first(50))
        .await
        .expect("federation.list_configs");
    client
        .federation()
        .list_configs_all(PageRequest::first(50))
        .await
        .expect("federation.list_configs auto-paging");

    // federation.create_config
    mount(&server, "POST", "/api/v1/federation-configs", 201, r#"{"attribute_map": {}, "client_id": "example", "created_at": "2026-08-26T00:00:00Z", "enabled": true, "id": "11111111-1111-4111-8111-111111111111", "protocol": "example", "provider": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "token_exchange": {"accepted_audiences": [], "enabled": true, "max_token_age_secs": 1, "scope_map": {}, "subject_mapping": "example"}, "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .federation()
        .create_config(&models::CreateFederationConfigRequest {
            allowed_algorithms: None,
            attribute_map: None,
            client_id: "example".to_string(),
            client_secret: Sensitive::new("example".to_string()),
            idp_signing_cert_pem: None,
            metadata_url: None,
            protocol: "example".to_string(),
            provider: "example".to_string(),
            token_exchange: None,
        })
        .await
        .expect("federation.create_config");

    // federation.get_config
    mount(&server, "GET", &format!("/api/v1/federation-configs/{EXAMPLE_ID}"), 200, r#"{"attribute_map": {}, "client_id": "example", "created_at": "2026-08-26T00:00:00Z", "enabled": true, "id": "11111111-1111-4111-8111-111111111111", "protocol": "example", "provider": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "token_exchange": {"accepted_audiences": [], "enabled": true, "max_token_age_secs": 1, "scope_map": {}, "subject_mapping": "example"}, "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .federation()
        .get_config(example_id())
        .await
        .expect("federation.get_config");

    // federation.update_config
    mount(&server, "PUT", &format!("/api/v1/federation-configs/{EXAMPLE_ID}"), 200, r#"{"attribute_map": {}, "client_id": "example", "created_at": "2026-08-26T00:00:00Z", "enabled": true, "id": "11111111-1111-4111-8111-111111111111", "protocol": "example", "provider": "example", "tenant_id": "11111111-1111-4111-8111-111111111111", "token_exchange": {"accepted_audiences": [], "enabled": true, "max_token_age_secs": 1, "scope_map": {}, "subject_mapping": "example"}, "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .federation()
        .update_config(
            example_id(),
            &models::UpdateFederationConfigRequest::default(),
        )
        .await
        .expect("federation.update_config");

    // federation.delete_config
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/federation-configs/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .federation()
        .delete_config(example_id())
        .await
        .expect("federation.delete_config");

    // federation.list_user_links
    mount(&server, "GET", &format!("/api/v1/federation-links/user/{EXAMPLE_ID}"), 200, r#"[{"created_at": "2026-08-26T00:00:00Z", "external_subject": "example", "federation_config_id": "11111111-1111-4111-8111-111111111111", "id": "11111111-1111-4111-8111-111111111111", "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z", "user_id": "11111111-1111-4111-8111-111111111111"}]"#).await;
    client
        .federation()
        .list_user_links(example_id())
        .await
        .expect("federation.list_user_links");

    // federation.delete_link
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/federation-links/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .federation()
        .delete_link(example_id())
        .await
        .expect("federation.delete_link");

    // federation.oidc_authorize
    mount(
        &server,
        "POST",
        "/api/v1/federation/oidc/authorize",
        200,
        r#"{"url": "example"}"#,
    )
    .await;
    client
        .federation()
        .oidc_authorize(&models::OidcAuthorizeRequest {
            config_id: example_id(),
            nonce: "example".to_string(),
            redirect_uri: "example".to_string(),
            state: "example".to_string(),
        })
        .await
        .expect("federation.oidc_authorize");

    // federation.oidc_callback
    mount(&server, "POST", "/api/v1/federation/oidc/callback", 200, r#"{"federation_link_id": "11111111-1111-4111-8111-111111111111", "newly_provisioned": true, "user_id": "11111111-1111-4111-8111-111111111111"}"#).await;
    client
        .federation()
        .oidc_callback(&models::OidcCallbackRequest {
            code: "example".to_string(),
            config_id: example_id(),
            nonce: "example".to_string(),
            redirect_uri: "example".to_string(),
            state: "example".to_string(),
        })
        .await
        .expect("federation.oidc_callback");
}

/// Reaches every operation in the `notification_rules` namespace.
#[tokio::test]
async fn notification_rules_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // notification_rules.list
    mount(&server, "GET", "/api/v1/notification-rules", 200, r#"{"items": [{"created_at": "2026-08-26T00:00:00Z", "description": "example", "enabled": true, "events": [], "id": "11111111-1111-4111-8111-111111111111", "name": "example", "recipient_emails": [], "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .notification_rules()
        .list(PageRequest::first(50))
        .await
        .expect("notification_rules.list");
    client
        .notification_rules()
        .list_all(PageRequest::first(50))
        .await
        .expect("notification_rules.list auto-paging");

    // notification_rules.create
    mount(&server, "POST", "/api/v1/notification-rules", 201, r#"{"created_at": "2026-08-26T00:00:00Z", "description": "example", "enabled": true, "events": [], "id": "11111111-1111-4111-8111-111111111111", "name": "example", "recipient_emails": [], "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .notification_rules()
        .create(&models::CreateNotificationRuleRequest {
            description: "example".to_string(),
            events: Vec::new(),
            name: "example".to_string(),
            recipient_emails: Vec::new(),
        })
        .await
        .expect("notification_rules.create");

    // notification_rules.get
    mount(&server, "GET", &format!("/api/v1/notification-rules/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "description": "example", "enabled": true, "events": [], "id": "11111111-1111-4111-8111-111111111111", "name": "example", "recipient_emails": [], "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .notification_rules()
        .get(example_id())
        .await
        .expect("notification_rules.get");

    // notification_rules.update
    mount(&server, "PUT", &format!("/api/v1/notification-rules/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "description": "example", "enabled": true, "events": [], "id": "11111111-1111-4111-8111-111111111111", "name": "example", "recipient_emails": [], "tenant_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .notification_rules()
        .update(
            example_id(),
            &models::UpdateNotificationRuleRequest::default(),
        )
        .await
        .expect("notification_rules.update");

    // notification_rules.delete
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/notification-rules/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .notification_rules()
        .delete(example_id())
        .await
        .expect("notification_rules.delete");
}

/// Reaches every operation in the `email_config` namespace.
#[tokio::test]
async fn email_config_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // email_config.get_org
    mount(&server, "GET", &format!("/api/v1/organizations/{ORG_ID}/email-config"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "enabled": true, "from_email": "example", "from_name": "example", "id": "11111111-1111-4111-8111-111111111111", "provider": {"host": "example", "port": 1, "starttls": true, "username": "example", "kind": "smtp"}, "scope": "Org", "scope_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .email_config()
        .get_org()
        .await
        .expect("email_config.get_org");

    // email_config.set_org
    mount(&server, "PUT", &format!("/api/v1/organizations/{ORG_ID}/email-config"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "enabled": true, "from_email": "example", "from_name": "example", "id": "11111111-1111-4111-8111-111111111111", "provider": {"host": "example", "port": 1, "starttls": true, "username": "example", "kind": "smtp"}, "scope": "Org", "scope_id": "11111111-1111-4111-8111-111111111111", "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .email_config()
        .set_org(&models::SetOrgEmailConfig {
            enabled: true,
            from_email: "example".to_string(),
            from_name: "example".to_string(),
            provider: models::ProviderConfig::Smtp(models::SmtpConfig {
                host: "example".to_string(),
                port: 1,
                starttls: true,
                username: "example".to_string(),
            }),
            reply_to: None,
        })
        .await
        .expect("email_config.set_org");

    // email_config.delete_org
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/organizations/{ORG_ID}/email-config"),
        204,
        "",
    )
    .await;
    client
        .email_config()
        .delete_org()
        .await
        .expect("email_config.delete_org");

    // email_config.test_org
    mount(
        &server,
        "POST",
        &format!("/api/v1/organizations/{ORG_ID}/email-config/test"),
        200,
        r#"{"provider": "example", "to": "example"}"#,
    )
    .await;
    client
        .email_config()
        .test_org()
        .await
        .expect("email_config.test_org");

    // email_config.get_tenant
    mount(
        &server,
        "GET",
        &format!("/api/v1/tenants/{TENANT_ID}/email-config"),
        200,
        r#"{}"#,
    )
    .await;
    client
        .email_config()
        .get_tenant()
        .await
        .expect("email_config.get_tenant");

    // email_config.set_tenant
    mount(
        &server,
        "PUT",
        &format!("/api/v1/tenants/{TENANT_ID}/email-config"),
        200,
        r#"{}"#,
    )
    .await;
    client
        .email_config()
        .set_tenant(&models::EmailConfigOverride::default())
        .await
        .expect("email_config.set_tenant");

    // email_config.delete_tenant
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/tenants/{TENANT_ID}/email-config"),
        204,
        "",
    )
    .await;
    client
        .email_config()
        .delete_tenant()
        .await
        .expect("email_config.delete_tenant");

    // email_config.test_tenant
    mount(
        &server,
        "POST",
        &format!("/api/v1/tenants/{TENANT_ID}/email-config/test"),
        200,
        r#"{"provider": "example", "to": "example"}"#,
    )
    .await;
    client
        .email_config()
        .test_tenant()
        .await
        .expect("email_config.test_tenant");
}

/// Reaches every operation in the `settings` namespace.
#[tokio::test]
async fn settings_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // settings.get_org
    mount(&server, "GET", &format!("/api/v1/organizations/{ORG_ID}/settings"), 200, r#"{"certificate": {"default_cert_validity_days": 1, "max_cert_validity_days": 1}, "created_at": "2026-08-26T00:00:00Z", "email": {"email_verification_grace_period_hours": 1, "email_verification_required": true}, "id": "11111111-1111-4111-8111-111111111111", "lockout": {"lockout_backoff_multiplier": 1.0, "lockout_duration_secs": 1, "max_failed_login_attempts": 1, "max_lockout_duration_secs": 1}, "mfa": {"mfa_challenge_lifetime_secs": 1, "mfa_enforced": true}, "notification": {"admin_notifications_enabled": true}, "opaque": {"opaque_ksf": "example", "opaque_mode": "example", "opaque_suite": "example"}, "password": {"hibp_check_enabled": true, "min_length": 1, "password_history_count": 1, "require_digits": true, "require_lowercase": true, "require_symbols": true, "require_uppercase": true}, "privacy": {"deletion_grace_period_days": 1}, "scope": "Org", "scope_id": "11111111-1111-4111-8111-111111111111", "token": {"access_token_lifetime_secs": 1, "refresh_token_lifetime_secs": 1}, "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client.settings().get_org().await.expect("settings.get_org");

    // settings.set_org
    mount(&server, "PUT", &format!("/api/v1/organizations/{ORG_ID}/settings"), 200, r#"{"certificate": {"default_cert_validity_days": 1, "max_cert_validity_days": 1}, "created_at": "2026-08-26T00:00:00Z", "email": {"email_verification_grace_period_hours": 1, "email_verification_required": true}, "id": "11111111-1111-4111-8111-111111111111", "lockout": {"lockout_backoff_multiplier": 1.0, "lockout_duration_secs": 1, "max_failed_login_attempts": 1, "max_lockout_duration_secs": 1}, "mfa": {"mfa_challenge_lifetime_secs": 1, "mfa_enforced": true}, "notification": {"admin_notifications_enabled": true}, "opaque": {"opaque_ksf": "example", "opaque_mode": "example", "opaque_suite": "example"}, "password": {"hibp_check_enabled": true, "min_length": 1, "password_history_count": 1, "require_digits": true, "require_lowercase": true, "require_symbols": true, "require_uppercase": true}, "privacy": {"deletion_grace_period_days": 1}, "scope": "Org", "scope_id": "11111111-1111-4111-8111-111111111111", "token": {"access_token_lifetime_secs": 1, "refresh_token_lifetime_secs": 1}, "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .settings()
        .set_org(&models::SetOrgSettings {
            access_token_lifetime_secs: 1,
            admin_notifications_enabled: true,
            default_cert_validity_days: 1,
            deletion_grace_period_days: None,
            email_verification_grace_period_hours: 1,
            email_verification_required: true,
            hibp_check_enabled: true,
            lockout_backoff_multiplier: 1.0,
            lockout_duration_secs: 1,
            max_cert_validity_days: 1,
            max_failed_login_attempts: 1,
            max_lockout_duration_secs: 1,
            mfa_challenge_lifetime_secs: 1,
            mfa_enforced: true,
            min_length: 1,
            opaque_ksf: None,
            opaque_mode: None,
            opaque_suite: None,
            password_history_count: 1,
            refresh_token_lifetime_secs: 1,
            require_digits: true,
            require_lowercase: true,
            require_symbols: true,
            require_uppercase: true,
        })
        .await
        .expect("settings.set_org");

    // settings.get_effective
    mount(&server, "GET", "/api/v1/settings", 200, r#"{"certificate": {"default_cert_validity_days": 1, "max_cert_validity_days": 1}, "created_at": "2026-08-26T00:00:00Z", "email": {"email_verification_grace_period_hours": 1, "email_verification_required": true}, "id": "11111111-1111-4111-8111-111111111111", "lockout": {"lockout_backoff_multiplier": 1.0, "lockout_duration_secs": 1, "max_failed_login_attempts": 1, "max_lockout_duration_secs": 1}, "mfa": {"mfa_challenge_lifetime_secs": 1, "mfa_enforced": true}, "notification": {"admin_notifications_enabled": true}, "opaque": {"opaque_ksf": "example", "opaque_mode": "example", "opaque_suite": "example"}, "password": {"hibp_check_enabled": true, "min_length": 1, "password_history_count": 1, "require_digits": true, "require_lowercase": true, "require_symbols": true, "require_uppercase": true}, "privacy": {"deletion_grace_period_days": 1}, "scope": "Org", "scope_id": "11111111-1111-4111-8111-111111111111", "token": {"access_token_lifetime_secs": 1, "refresh_token_lifetime_secs": 1}, "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .settings()
        .get_effective()
        .await
        .expect("settings.get_effective");

    // settings.set_effective
    mount(&server, "PUT", "/api/v1/settings", 200, r#"{"certificate": {"default_cert_validity_days": 1, "max_cert_validity_days": 1}, "created_at": "2026-08-26T00:00:00Z", "email": {"email_verification_grace_period_hours": 1, "email_verification_required": true}, "id": "11111111-1111-4111-8111-111111111111", "lockout": {"lockout_backoff_multiplier": 1.0, "lockout_duration_secs": 1, "max_failed_login_attempts": 1, "max_lockout_duration_secs": 1}, "mfa": {"mfa_challenge_lifetime_secs": 1, "mfa_enforced": true}, "notification": {"admin_notifications_enabled": true}, "opaque": {"opaque_ksf": "example", "opaque_mode": "example", "opaque_suite": "example"}, "password": {"hibp_check_enabled": true, "min_length": 1, "password_history_count": 1, "require_digits": true, "require_lowercase": true, "require_symbols": true, "require_uppercase": true}, "privacy": {"deletion_grace_period_days": 1}, "scope": "Org", "scope_id": "11111111-1111-4111-8111-111111111111", "token": {"access_token_lifetime_secs": 1, "refresh_token_lifetime_secs": 1}, "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .settings()
        .set_effective(&models::TenantSettingsOverride::default())
        .await
        .expect("settings.set_effective");

    // settings.get_tenant_override
    mount(
        &server,
        "GET",
        &format!("/api/v1/tenants/{TENANT_ID}/settings"),
        200,
        r#"{}"#,
    )
    .await;
    client
        .settings()
        .get_tenant_override()
        .await
        .expect("settings.get_tenant_override");

    // settings.set_tenant_override
    mount(
        &server,
        "PUT",
        &format!("/api/v1/tenants/{TENANT_ID}/settings"),
        200,
        r#"{}"#,
    )
    .await;
    client
        .settings()
        .set_tenant_override(&models::TenantSettingsOverride::default())
        .await
        .expect("settings.set_tenant_override");

    // settings.delete_tenant_override
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/tenants/{TENANT_ID}/settings"),
        204,
        "",
    )
    .await;
    client
        .settings()
        .delete_tenant_override()
        .await
        .expect("settings.delete_tenant_override");
}

/// Reaches every operation in the `scim_tokens` namespace.
#[tokio::test]
async fn scim_tokens_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // scim_tokens.list
    mount(&server, "GET", "/api/v1/scim-tokens", 200, r#"[{"created_at": "2026-08-26T00:00:00Z", "created_by": "11111111-1111-4111-8111-111111111111", "expires_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "name": "example", "status": "active", "tenant_id": "11111111-1111-4111-8111-111111111111", "user_id": "11111111-1111-4111-8111-111111111111"}]"#).await;
    client.scim_tokens().list().await.expect("scim_tokens.list");

    // scim_tokens.create
    mount(&server, "POST", "/api/v1/scim-tokens", 201, r#"{"created_at": "2026-08-26T00:00:00Z", "created_by": "11111111-1111-4111-8111-111111111111", "expires_at": "2026-08-26T00:00:00Z", "id": "11111111-1111-4111-8111-111111111111", "name": "example", "status": "active", "tenant_id": "11111111-1111-4111-8111-111111111111", "user_id": "11111111-1111-4111-8111-111111111111", "provisioning_token": "example"}"#).await;
    client
        .scim_tokens()
        .create(&models::CreateScimTokenRequest {
            expires_in_days: None,
            name: "example".to_string(),
            user_id: example_id(),
        })
        .await
        .expect("scim_tokens.create");

    // scim_tokens.revoke
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/scim-tokens/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .scim_tokens()
        .revoke(example_id())
        .await
        .expect("scim_tokens.revoke");
}

/// Reaches every operation in the `reactors` namespace.
#[tokio::test]
async fn reactors_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // reactors.list
    mount(&server, "GET", "/api/v1/reactors", 200, r#"{"items": [{"created_at": "2026-08-26T00:00:00Z", "description": "example", "enabled": true, "events": [], "failure_policy": "fail_closed", "id": "11111111-1111-4111-8111-111111111111", "mode": "intercept", "name": "example", "priority": 1, "recent_timeout_count": 1, "recent_veto_count": 1, "tenant_id": "11111111-1111-4111-8111-111111111111", "timeout_ms": 1, "updated_at": "2026-08-26T00:00:00Z"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .reactors()
        .list(PageRequest::first(50))
        .await
        .expect("reactors.list");
    client
        .reactors()
        .list_all(PageRequest::first(50))
        .await
        .expect("reactors.list auto-paging");

    // reactors.create
    mount(&server, "POST", "/api/v1/reactors", 201, r#"{"created_at": "2026-08-26T00:00:00Z", "description": "example", "enabled": true, "events": [], "failure_policy": "fail_closed", "id": "11111111-1111-4111-8111-111111111111", "mode": "intercept", "name": "example", "priority": 1, "recent_timeout_count": 1, "recent_veto_count": 1, "tenant_id": "11111111-1111-4111-8111-111111111111", "timeout_ms": 1, "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .reactors()
        .create(&models::CreateReactorRequest {
            description: None,
            enabled: None,
            events: Vec::new(),
            failure_policy: None,
            mode: models::ReactorMode::Intercept,
            name: "example".to_string(),
            priority: None,
            timeout_ms: None,
        })
        .await
        .expect("reactors.create");

    // reactors.get
    mount(&server, "GET", &format!("/api/v1/reactors/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "description": "example", "enabled": true, "events": [], "failure_policy": "fail_closed", "id": "11111111-1111-4111-8111-111111111111", "mode": "intercept", "name": "example", "priority": 1, "recent_timeout_count": 1, "recent_veto_count": 1, "tenant_id": "11111111-1111-4111-8111-111111111111", "timeout_ms": 1, "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .reactors()
        .get(example_id())
        .await
        .expect("reactors.get");

    // reactors.update
    mount(&server, "PUT", &format!("/api/v1/reactors/{EXAMPLE_ID}"), 200, r#"{"created_at": "2026-08-26T00:00:00Z", "description": "example", "enabled": true, "events": [], "failure_policy": "fail_closed", "id": "11111111-1111-4111-8111-111111111111", "mode": "intercept", "name": "example", "priority": 1, "recent_timeout_count": 1, "recent_veto_count": 1, "tenant_id": "11111111-1111-4111-8111-111111111111", "timeout_ms": 1, "updated_at": "2026-08-26T00:00:00Z"}"#).await;
    client
        .reactors()
        .update(example_id(), &models::UpdateReactorRequest::default())
        .await
        .expect("reactors.update");

    // reactors.delete
    mount(
        &server,
        "DELETE",
        &format!("/api/v1/reactors/{EXAMPLE_ID}"),
        204,
        "",
    )
    .await;
    client
        .reactors()
        .delete(example_id())
        .await
        .expect("reactors.delete");

    // reactors.list_events
    mount(&server, "GET", "/api/v1/reactors/events", 200, r#"[{"default_failure_policy": "fail_closed", "description": "example", "interceptable": true, "mutable": true, "mutable_fields": [], "name": "example"}]"#).await;
    client
        .reactors()
        .list_events()
        .await
        .expect("reactors.list_events");
}

/// Reaches every operation in the `webauthn_policy` namespace.
#[tokio::test]
async fn webauthn_policy_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // webauthn_policy.get
    mount(&server, "GET", &format!("/api/v1/tenants/{TENANT_ID}/webauthn/attestation-policy"), 200, r#"{"block_revoked_status": true, "mode": "none", "require_fido_certified": true, "effective_unknown_aaguid": "allow"}"#).await;
    client
        .webauthn_policy()
        .get()
        .await
        .expect("webauthn_policy.get");

    // webauthn_policy.set
    mount(
        &server,
        "PUT",
        &format!("/api/v1/tenants/{TENANT_ID}/webauthn/attestation-policy"),
        200,
        r#"{"block_revoked_status": true, "mode": "none", "require_fido_certified": true}"#,
    )
    .await;
    client
        .webauthn_policy()
        .set(&models::WebauthnAttestationPolicy {
            allowed_aaguids: None,
            block_revoked_status: true,
            blocked_aaguids: None,
            min_certification: None,
            mode: models::AttestationMode::None,
            require_fido_certified: true,
            unknown_aaguid: None,
        })
        .await
        .expect("webauthn_policy.set");

    // webauthn_policy.compliance_report
    mount(&server, "GET", &format!("/api/v1/tenants/{TENANT_ID}/webauthn/compliance-report"), 200, r#"[{"compliant": true, "credential_id": "11111111-1111-4111-8111-111111111111", "name": "example", "user_id": "11111111-1111-4111-8111-111111111111"}]"#).await;
    client
        .webauthn_policy()
        .compliance_report()
        .await
        .expect("webauthn_policy.compliance_report");
}

/// Reaches every operation in the `audit` namespace.
#[tokio::test]
async fn audit_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // audit.list
    mount(&server, "GET", "/api/v1/audit-logs", 200, r#"{"items": [{"action": "example", "actor_id": "11111111-1111-4111-8111-111111111111", "actor_type": "User", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "outcome": "Success", "tenant_id": "11111111-1111-4111-8111-111111111111", "timestamp": "2026-08-26T00:00:00Z"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .audit()
        .list(&audit::AuditListFilter::default(), PageRequest::first(50))
        .await
        .expect("audit.list");
    client
        .audit()
        .list_all(&audit::AuditListFilter::default(), PageRequest::first(50))
        .await
        .expect("audit.list auto-paging");

    // audit.list_system
    mount(&server, "GET", "/api/v1/audit-logs/system", 200, r#"{"items": [{"action": "example", "actor_id": "11111111-1111-4111-8111-111111111111", "actor_type": "User", "id": "11111111-1111-4111-8111-111111111111", "metadata": {}, "outcome": "Success", "tenant_id": "11111111-1111-4111-8111-111111111111", "timestamp": "2026-08-26T00:00:00Z"}], "total": 1, "offset": 0, "limit": 50}"#).await;
    client
        .audit()
        .list_system(
            &audit::AuditListSystemFilter::default(),
            PageRequest::first(50),
        )
        .await
        .expect("audit.list_system");
    client
        .audit()
        .list_system_all(
            &audit::AuditListSystemFilter::default(),
            PageRequest::first(50),
        )
        .await
        .expect("audit.list_system auto-paging");
}

/// Reaches every operation in the `privacy` namespace.
#[tokio::test]
async fn privacy_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // privacy.request_export
    mount(&server, "POST", "/api/v1/account/export", 200, "").await;
    client
        .privacy()
        .request_export(&serde_json::json!({}))
        .await
        .expect("privacy.request_export");

    // privacy.download_export
    mount(&server, "GET", "/api/v1/account/export/example", 200, "").await;
    client
        .privacy()
        .download_export("example")
        .await
        .expect("privacy.download_export");

    // privacy.request_delete
    mount(&server, "POST", "/api/v1/account/delete", 200, "").await;
    client
        .privacy()
        .request_delete(&serde_json::json!({}))
        .await
        .expect("privacy.request_delete");

    // privacy.cancel_delete
    mount(
        &server,
        "GET",
        "/api/v1/auth/account/delete/cancel",
        200,
        "",
    )
    .await;
    client
        .privacy()
        .cancel_delete("example")
        .await
        .expect("privacy.cancel_delete");
}

/// Reaches every operation in the `platform` namespace.
#[tokio::test]
async fn platform_surface() {
    let server = MockServer::start().await;
    let client = logged_in_client(&server).await;

    // platform.health
    mount(&server, "GET", "/health", 200, r#"{"status": "example"}"#).await;
    client.platform().health().await.expect("platform.health");

    // platform.ready
    mount(
        &server,
        "GET",
        "/ready",
        200,
        r#"{"database": "example", "status": "example"}"#,
    )
    .await;
    client.platform().ready().await.expect("platform.ready");

    // platform.mds_status
    mount(
        &server,
        "GET",
        "/api/v1/mds/status",
        200,
        r#"{"entry_count": 1, "stale": true}"#,
    )
    .await;
    client
        .platform()
        .mds_status()
        .await
        .expect("platform.mds_status");

    // platform.mds_refresh
    mount(
        &server,
        "POST",
        "/api/v1/mds/refresh",
        200,
        r#"{"entry_count": 1, "no": 1, "outcome": "initial"}"#,
    )
    .await;
    client
        .platform()
        .mds_refresh()
        .await
        .expect("platform.mds_refresh");
}
