//! The SSF receiver helper — CONTRACT.md §32.8's eight helper tests.
//!
//! Every key is an Ed25519 key generated by the test from fresh randomness,
//! and every SET is signed here: no key literal, no captured token.

#![cfg(feature = "rest")]

use std::collections::BTreeMap;
use std::sync::{Arc, Mutex};
use std::time::Duration;

use axiam_sdk::client::AxiamClient;
use axiam_sdk::ssf::{
    ReplayStore, SetErr, SsfKeySource, SsfPollOptions, SsfReceiver, SsfReceiverConfig, event_types,
};
use axiam_sdk::{AxiamError, Sensitive, SetFailureReason};
use base64::Engine as _;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use jsonwebtoken::{Algorithm, EncodingKey, Header};
use serde_json::{Value, json};
use uuid::Uuid;
use wiremock::matchers::{method, path};
use wiremock::{Mock, MockServer, Request, ResponseTemplate};

const ISSUER: &str = "https://iam.example.test/t/22222222-2222-4222-8222-222222222222";
const AUDIENCE: &str = "https://rp.example.test";
const ED25519_PKCS8_PREFIX: [u8; 16] = [
    0x30, 0x2e, 0x02, 0x01, 0x00, 0x30, 0x05, 0x06, 0x03, 0x2b, 0x65, 0x70, 0x04, 0x22, 0x04, 0x20,
];

struct Key {
    kid: String,
    seed: [u8; 32],
}

impl Key {
    fn generate() -> Self {
        let mut seed = [0u8; 32];
        seed[..16].copy_from_slice(Uuid::new_v4().as_bytes());
        seed[16..].copy_from_slice(Uuid::new_v4().as_bytes());
        Self {
            kid: format!("k-{}", Uuid::new_v4().simple()),
            seed,
        }
    }

    fn jwk(&self) -> Value {
        let public = ed25519_dalek::SigningKey::from_bytes(&self.seed).verifying_key();
        json!({"kty": "OKP", "crv": "Ed25519", "alg": "EdDSA", "use": "sig",
               "kid": self.kid, "x": URL_SAFE_NO_PAD.encode(public.to_bytes())})
    }

    fn encoding_key(&self) -> EncodingKey {
        let mut der = ED25519_PKCS8_PREFIX.to_vec();
        der.extend_from_slice(&self.seed);
        EncodingKey::from_ed_der(&der)
    }

    fn sign(&self, header: Value, claims: &Value) -> String {
        let h = URL_SAFE_NO_PAD.encode(serde_json::to_vec(&header).unwrap());
        let p = URL_SAFE_NO_PAD.encode(serde_json::to_vec(claims).unwrap());
        let input = format!("{h}.{p}");
        let sig =
            jsonwebtoken::crypto::sign(input.as_bytes(), &self.encoding_key(), Algorithm::EdDSA)
                .unwrap();
        format!("{input}.{sig}")
    }

    fn sign_set(&self, claims: &Value) -> String {
        self.sign(
            json!({"alg": "EdDSA", "typ": "secevent+jwt", "kid": self.kid}),
            claims,
        )
    }
}

fn claims() -> Value {
    json!({
        "iss": ISSUER, "aud": AUDIENCE, "iat": 1_791_500_000,
        "jti": Uuid::new_v4().simple().to_string(), "txn": "t-1",
        "sub_id": {"format": "iss_sub", "iss": ISSUER, "sub": Uuid::new_v4()},
        "events": {event_types::SESSION_REVOKED: {"event_timestamp": 1_791_500_000}},
    })
}

fn with(mut v: Value, k: &str, x: Value) -> Value {
    v[k] = x;
    v
}

fn without(mut v: Value, k: &str) -> Value {
    v.as_object_mut().unwrap().remove(k);
    v
}

/// Serve `keys` at `/oauth2/jwks` and count the fetches.
async fn jwks(server: &MockServer, keys: Vec<Value>) -> Arc<Mutex<usize>> {
    let hits = Arc::new(Mutex::new(0usize));
    let sink = Arc::clone(&hits);
    Mock::given(method("GET"))
        .and(path("/oauth2/jwks"))
        .respond_with(move |_: &Request| {
            *sink.lock().unwrap() += 1;
            ResponseTemplate::new(200).set_body_json(json!({"keys": keys}))
        })
        .mount(server)
        .await;
    hits
}

fn client(server: &MockServer) -> AxiamClient {
    AxiamClient::builder()
        .base_url(server.uri())
        .unwrap()
        .tenant_id(Uuid::new_v4())
        .build()
        .unwrap()
}

fn receiver(server: &MockServer) -> SsfReceiver {
    let token = format!("cc-{}", Uuid::new_v4().simple());
    let mut config = SsfReceiverConfig::new(
        ISSUER,
        AUDIENCE,
        SsfKeySource::JwksUri(format!("{}/oauth2/jwks", server.uri())),
    );
    config.access_token_provider = Some(Arc::new(move || {
        let t = token.clone();
        Box::pin(async move { Ok(Sensitive::new(t)) })
    }));
    SsfReceiver::new(&client(server), config).unwrap()
}

async fn reason(receiver: &SsfReceiver, set: &str) -> SetFailureReason {
    let e = receiver.verify_set(set).await.unwrap_err();
    assert!(matches!(e, AxiamError::Auth { .. }), "{e}");
    e.set_failure_reason().expect("a SET refusal")
}

// ── 1 ──
#[tokio::test]
async fn a_set_signed_by_the_jwks_key_verifies_into_its_claims() {
    let server = MockServer::start().await;
    let key = Key::generate();
    jwks(&server, vec![key.jwk()]).await;
    let c = claims();
    let event = receiver(&server)
        .verify_set(&key.sign_set(&c))
        .await
        .expect("verifies");
    assert_eq!(event.jti, c["jti"]);
    assert_eq!(event.iat, 1_791_500_000);
    assert_eq!(event.iss, ISSUER);
    assert_eq!(event.aud, json!(AUDIENCE));
    assert_eq!(event.txn.as_deref(), Some("t-1"));
    assert_eq!(event.event_type, event_types::SESSION_REVOKED);
    assert_eq!(event.event, c["events"][event_types::SESSION_REVOKED]);
    assert_eq!(event.sub_id, c["sub_id"]);

    // An `aud` array containing the audience verifies too, and so does the
    // media-type spelling of `typ`.
    let arr = with(claims(), "aud", json!(["other", AUDIENCE]));
    let set = key.sign(
        json!({"alg": "EdDSA", "typ": "Application/SecEvent+JWT", "kid": key.kid}),
        &arr,
    );
    receiver(&server).verify_set(&set).await.expect("array aud");
}

// ── 2 ──
#[tokio::test]
async fn a_wrong_typ_or_alg_is_refused_in_that_order() {
    let server = MockServer::start().await;
    let key = Key::generate();
    jwks(&server, vec![key.jwk()]).await;
    let r = receiver(&server);
    let c = claims();
    for header in [
        json!({"alg": "EdDSA", "kid": key.kid}),
        json!({"alg": "EdDSA", "typ": "JWT", "kid": key.kid}),
    ] {
        assert_eq!(
            reason(&r, &key.sign(header, &c)).await,
            SetFailureReason::InvalidType
        );
    }
    let p = URL_SAFE_NO_PAD.encode(serde_json::to_vec(&c).unwrap());
    let none = format!(
        "{}.{p}.",
        URL_SAFE_NO_PAD.encode(br#"{"alg":"none","typ":"secevent+jwt"}"#)
    );
    assert_eq!(reason(&r, &none).await, SetFailureReason::InvalidKey);
    let hs = jsonwebtoken::encode(
        &{
            let mut h = Header::new(Algorithm::HS256);
            h.typ = Some("secevent+jwt".into());
            h.kid = Some(key.kid.clone());
            h
        },
        &c,
        &EncodingKey::from_secret(Uuid::new_v4().as_bytes()),
    )
    .unwrap();
    assert_eq!(reason(&r, &hs).await, SetFailureReason::InvalidKey);
    assert_eq!(reason(&r, "a.b").await, SetFailureReason::Malformed);
    assert_eq!(reason(&r, "!!.@@.##").await, SetFailureReason::Malformed);
}

// ── 3 ──
#[tokio::test]
async fn another_key_or_a_tampered_payload_is_invalid_key() {
    let server = MockServer::start().await;
    let key = Key::generate();
    let rogue = Key {
        kid: key.kid.clone(),
        seed: Key::generate().seed,
    };
    jwks(&server, vec![key.jwk()]).await;
    let r = receiver(&server);
    assert_eq!(
        reason(&r, &rogue.sign_set(&claims())).await,
        SetFailureReason::InvalidKey
    );
    let good = key.sign_set(&claims());
    let mut parts: Vec<String> = good.split('.').map(str::to_owned).collect();
    parts[1] =
        URL_SAFE_NO_PAD.encode(serde_json::to_vec(&with(claims(), "txn", json!("x"))).unwrap());
    assert_eq!(
        reason(&r, &parts.join(".")).await,
        SetFailureReason::InvalidKey
    );
}

// ── 4 ──
#[tokio::test]
async fn another_issuer_or_audience_is_refused() {
    let server = MockServer::start().await;
    let key = Key::generate();
    jwks(&server, vec![key.jwk()]).await;
    let r = receiver(&server);
    let other_iss = with(claims(), "iss", json!("https://iam.example.test"));
    assert_eq!(
        reason(&r, &key.sign_set(&other_iss)).await,
        SetFailureReason::InvalidIssuer
    );
    let other_aud = with(claims(), "aud", json!(["https://elsewhere.test"]));
    assert_eq!(
        reason(&r, &key.sign_set(&other_aud)).await,
        SetFailureReason::InvalidAudience
    );
}

// ── 5 ──
#[tokio::test]
async fn exp_sub_two_events_or_no_jti_is_invalid_request() {
    let server = MockServer::start().await;
    let key = Key::generate();
    jwks(&server, vec![key.jwk()]).await;
    let r = receiver(&server);
    let two = with(
        claims(),
        "events",
        json!({event_types::ACCOUNT_DISABLED: {}, event_types::ACCOUNT_PURGED: {}}),
    );
    for c in [
        with(claims(), "exp", json!(1_891_500_000)),
        with(claims(), "sub", json!("u")),
        two,
        without(claims(), "jti"),
        without(claims(), "iat"),
        without(claims(), "sub_id"),
    ] {
        assert_eq!(
            reason(&r, &key.sign_set(&c)).await,
            SetFailureReason::InvalidRequest,
            "{c}"
        );
    }
}

// ── 6 ──
#[tokio::test]
async fn a_replay_is_refused_and_a_short_window_is_refused_at_configuration() {
    let server = MockServer::start().await;
    let key = Key::generate();
    jwks(&server, vec![key.jwk()]).await;
    let r = receiver(&server);
    let set = key.sign_set(&claims());
    r.verify_set(&set).await.expect("first time");
    assert_eq!(reason(&r, &set).await, SetFailureReason::Replayed);

    let mut short = SsfReceiverConfig::new(
        ISSUER,
        AUDIENCE,
        SsfKeySource::JwksUri(format!("{}/oauth2/jwks", server.uri())),
    );
    short.replay_window = Duration::from_secs(6 * 24 * 60 * 60);
    let e = SsfReceiver::new(&client(&server), short).unwrap_err();
    assert!(e.validation().is_some(), "{e}");
}

// ── 7 ──
#[tokio::test]
async fn an_unknown_kid_costs_one_refetch_and_a_second_one_none() {
    let server = MockServer::start().await;
    let key = Key::generate();
    let hits = jwks(&server, vec![key.jwk()]).await;
    let r = receiver(&server);
    r.verify_set(&key.sign_set(&claims()))
        .await
        .expect("primes the cache");
    assert_eq!(*hits.lock().unwrap(), 1);

    let stranger = Key::generate();
    assert_eq!(
        reason(&r, &stranger.sign_set(&claims())).await,
        SetFailureReason::InvalidKey
    );
    assert_eq!(*hits.lock().unwrap(), 2, "exactly one refetch");
    let another = Key::generate();
    assert_eq!(
        reason(&r, &another.sign_set(&claims())).await,
        SetFailureReason::InvalidKey
    );
    assert_eq!(*hits.lock().unwrap(), 2, "no refetch within the minute");
}

// ── 8 ──
#[tokio::test]
async fn poll_passes_ack_and_set_errs_through_and_sorts_the_answer() {
    let server = MockServer::start().await;
    let key = Key::generate();
    jwks(&server, vec![key.jwk()]).await;
    let stream = Uuid::new_v4().to_string();
    let good = claims();
    let bad = with(claims(), "iss", json!("https://impostor.test"));
    let good_jti = good["jti"].as_str().unwrap().to_string();
    let bad_jti = bad["jti"].as_str().unwrap().to_string();
    let reply = json!({
        "sets": {good_jti.clone(): key.sign_set(&good), bad_jti.clone(): key.sign_set(&bad)},
        "moreAvailable": true,
    });
    let seen = Arc::new(Mutex::new(Vec::<(Value, Option<String>)>::new()));
    let sink = Arc::clone(&seen);
    Mock::given(method("POST"))
        .and(path(format!("/ssf/v1/poll/{stream}")))
        .respond_with(move |req: &Request| {
            sink.lock().unwrap().push((
                serde_json::from_slice(&req.body).unwrap(),
                req.headers
                    .get("authorization")
                    .map(|v| v.to_str().unwrap().to_owned()),
            ));
            ResponseTemplate::new(200).set_body_json(reply.clone())
        })
        .mount(&server)
        .await;

    let r = receiver(&server);
    let mut errs = BTreeMap::new();
    errs.insert(
        "old-1".to_string(),
        SetErr::from_reason(SetFailureReason::Replayed),
    );
    let result = r
        .poll(
            &stream,
            SsfPollOptions {
                max_events: Some(10),
                return_immediately: Some(true),
                ack: Some(vec!["done-1".into(), "done-2".into()]),
                set_errs: Some(errs),
            },
        )
        .await
        .expect("poll");
    assert!(result.more_available);
    assert_eq!(result.events.len(), 1);
    assert_eq!(result.events[0].jti, good_jti);
    assert_eq!(result.refused.len(), 1);
    assert_eq!(result.refused[0].jti, bad_jti);
    assert_eq!(result.refused[0].reason, SetFailureReason::InvalidIssuer);
    {
        let sent = seen.lock().unwrap();
        assert_eq!(sent.len(), 1);
        assert_eq!(
            sent[0].0,
            json!({"maxEvents": 10, "returnImmediately": true, "ack": ["done-1", "done-2"],
                   "setErrs": {"old-1": {"err": "invalid_request"}}}),
            "exactly as given, and nothing acknowledged on the caller's behalf"
        );
        assert!(sent[0].1.as_deref().unwrap().starts_with("Bearer cc-"));
    }

    // A second poll with no arguments sends an empty object: still no ack.
    r.poll(&stream, SsfPollOptions::default())
        .await
        .expect("again");
    assert_eq!(seen.lock().unwrap()[1].0, json!({}));
}

/// A [`ReplayStore`] the test can look into.
#[derive(Default)]
struct InspectableStore {
    seen: Mutex<Vec<String>>,
}

impl ReplayStore for InspectableStore {
    fn check_and_record(&self, jti: &str, _window: Duration) -> bool {
        let mut seen = self.seen.lock().unwrap();
        if seen.iter().any(|j| j == jti) {
            return false;
        }
        seen.push(jti.to_string());
        true
    }
}

// ── 8, the two-SET batch (contract 1.59, §34.2 P1) ──
//
// The second SET names a `kid` the cached JWKS lacks, and the refetch that
// unknown `kid` triggers fails. That failure is no verdict on either SET, so
// `poll` may not leave the first SET's `jti` recorded unless it returns it:
// recorded and unreturned, the event is refused `replayed` when the
// transmitter offers it again, and lost.
#[tokio::test]
async fn poll_never_keeps_a_jti_it_does_not_return_when_a_later_key_fetch_fails() {
    let server = MockServer::start().await;
    let key = Key::generate();
    let jwks_hits = Arc::new(Mutex::new(0usize));
    let sink = Arc::clone(&jwks_hits);
    let keys = vec![key.jwk()];
    // The first fetch serves the key; every later one fails.
    Mock::given(method("GET"))
        .and(path("/oauth2/jwks"))
        .respond_with(move |_: &Request| {
            let mut hits = sink.lock().unwrap();
            *hits += 1;
            if *hits == 1 {
                ResponseTemplate::new(200).set_body_json(json!({"keys": keys}))
            } else {
                ResponseTemplate::new(503)
            }
        })
        .mount(&server)
        .await;
    let stream = Uuid::new_v4().to_string();
    // `a-` and `b-` keep the batch's order the same whatever map the
    // transmitter's JSON is read into.
    let first = with(
        claims(),
        "jti",
        json!(format!("a-{}", Uuid::new_v4().simple())),
    );
    let second = with(
        claims(),
        "jti",
        json!(format!("b-{}", Uuid::new_v4().simple())),
    );
    let first_jti = first["jti"].as_str().unwrap().to_string();
    let second_jti = second["jti"].as_str().unwrap().to_string();
    let stranger = Key::generate();
    let reply = json!({
        "sets": {
            first_jti.clone(): key.sign_set(&first),
            second_jti.clone(): stranger.sign_set(&second),
        },
        "moreAvailable": false,
    });
    Mock::given(method("POST"))
        .and(path(format!("/ssf/v1/poll/{stream}")))
        .respond_with(ResponseTemplate::new(200).set_body_json(reply))
        .mount(&server)
        .await;

    let store = Arc::new(InspectableStore::default());
    let token = format!("cc-{}", Uuid::new_v4().simple());
    let mut config = SsfReceiverConfig::new(
        ISSUER,
        AUDIENCE,
        SsfKeySource::JwksUri(format!("{}/oauth2/jwks", server.uri())),
    );
    config.access_token_provider = Some(Arc::new(move || {
        let t = token.clone();
        Box::pin(async move { Ok(Sensitive::new(t)) })
    }));
    config.replay_store = Some(store.clone());
    let r = SsfReceiver::new(&client(&server), config).unwrap();

    let outcome = r.poll(&stream, SsfPollOptions::default()).await;
    assert_eq!(
        *jwks_hits.lock().unwrap(),
        2,
        "the cold fill, then the one refetch the unknown kid costs"
    );
    let recorded = store.seen.lock().unwrap().clone();
    match outcome {
        Ok(result) => {
            let returned: Vec<&str> = result.events.iter().map(|e| e.jti.as_str()).collect();
            for jti in &recorded {
                assert!(
                    returned.contains(&jti.as_str()),
                    "{jti} is recorded but not returned"
                );
            }
            assert!(
                !result.refused.iter().any(|r| r.jti == second_jti),
                "a failed key fetch is no verdict on the second SET"
            );
        }
        Err(e) => {
            assert!(
                e.set_failure_reason().is_none(),
                "a failed key fetch is no verdict: {e}"
            );
            assert!(
                !recorded.contains(&first_jti),
                "the first SET's jti is recorded, but the poll returned nothing"
            );
        }
    }
    assert!(
        !recorded.contains(&second_jti),
        "the unjudged SET is not recorded"
    );
}

// ── §32.7 step 9 and §34.2 P4: a store that cannot answer fails closed ──
//
// `ReplayStore::check_and_record` returns `bool` and cannot report a failure,
// which conforms only if its documentation tells an implementer to answer
// "already seen" when it cannot answer. The documentation is pinned here, and
// so is what that answer does: a refusal, never an acceptance.

/// A store whose backend is down, answering as the trait's documentation says.
struct UnreachableStore;

impl ReplayStore for UnreachableStore {
    fn check_and_record(&self, _jti: &str, _window: Duration) -> bool {
        false
    }
}

#[test]
fn the_replay_store_documentation_says_fail_closed() {
    let source = include_str!("../src/ssf.rs");
    let start = source
        .find("pub trait ReplayStore")
        .expect("the trait is declared");
    let doc_start = source[..start]
        .rfind("\n\n")
        .expect("the trait's documentation");
    let doc = &source[doc_start..start];
    for needle in ["cannot answer", "return `false`", "fail closed"] {
        assert!(doc.contains(needle), "ReplayStore's docs lack {needle:?}");
    }
    let readme = include_str!("../README.md");
    assert!(
        readme.contains("unbounded in count"),
        "the README says the in-memory store is unbounded in count (§34.2 P4)"
    );
}

#[tokio::test]
async fn a_store_that_cannot_answer_refuses_and_never_accepts() {
    let server = MockServer::start().await;
    let key = Key::generate();
    jwks(&server, vec![key.jwk()]).await;
    let mut config = SsfReceiverConfig::new(
        ISSUER,
        AUDIENCE,
        SsfKeySource::JwksUri(format!("{}/oauth2/jwks", server.uri())),
    );
    config.replay_store = Some(Arc::new(UnreachableStore));
    let r = SsfReceiver::new(&client(&server), config).unwrap();
    assert_eq!(
        reason(&r, &key.sign_set(&claims())).await,
        SetFailureReason::Replayed
    );
}

#[tokio::test]
async fn poll_is_not_retried_on_400() {
    let server = MockServer::start().await;
    let stream = "s-1";
    let hits = Arc::new(Mutex::new(0usize));
    let sink = Arc::clone(&hits);
    Mock::given(method("POST"))
        .and(path(format!("/ssf/v1/poll/{stream}")))
        .respond_with(move |_: &Request| {
            *sink.lock().unwrap() += 1;
            ResponseTemplate::new(400).set_body_json(json!({"error": "push stream"}))
        })
        .mount(&server)
        .await;
    let e = receiver(&server)
        .poll(stream, SsfPollOptions::default())
        .await
        .unwrap_err();
    assert!(e.validation().is_some(), "{e}");
    assert_eq!(*hits.lock().unwrap(), 1);
}

#[tokio::test]
async fn discovery_supplies_the_jwks_uri_and_must_name_the_issuer() {
    let server = MockServer::start().await;
    let key = Key::generate();
    jwks(&server, vec![key.jwk()]).await;
    Mock::given(method("GET"))
        .and(path("/.well-known/ssf-configuration"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "issuer": ISSUER, "jwks_uri": format!("{}/oauth2/jwks", server.uri()),
        })))
        .mount(&server)
        .await;
    let config = SsfReceiverConfig::new(
        ISSUER,
        AUDIENCE,
        SsfKeySource::DiscoveryUrl(format!("{}/.well-known/ssf-configuration", server.uri())),
    );
    let r = SsfReceiver::new(&client(&server), config).unwrap();
    r.verify_set(&key.sign_set(&claims()))
        .await
        .expect("via discovery");

    let wrong = SsfReceiverConfig::new(
        "https://someone-else.test",
        AUDIENCE,
        SsfKeySource::DiscoveryUrl(format!("{}/.well-known/ssf-configuration", server.uri())),
    );
    let r = SsfReceiver::new(&client(&server), wrong).unwrap();
    let e = r.verify_set(&key.sign_set(&claims())).await.unwrap_err();
    assert!(matches!(e, AxiamError::Network { .. }) && e.set_failure_reason().is_none());
    // A poll with no token provider is refused locally.
    let e = r.poll("s", SsfPollOptions::default()).await.unwrap_err();
    assert!(matches!(e, AxiamError::Auth { .. }));
    // Debug never shows the provider.
    assert!(format!("{r:?}").contains("SsfReceiver"));
}
