// @generated by tools/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate
// with `tools/gen_management.py`; CI verifies the committed output is current.

//! One handle per §27 namespace, and the accessors that reach them.
//!
//! §27.2 makes this namespacing normative rather than stylistic: twenty
//! namespaces have a `list` and fourteen a `get`, so flattening 147
//! operations onto the client would need a disambiguating prefix invented
//! once per operation -- and would bury the eight §1 methods most callers
//! actually want under five times as many they do not.

pub mod audit;
pub mod ca_certificates;
pub mod certificates;
pub mod email_config;
pub mod federation;
pub mod groups;
pub mod notification_rules;
pub mod oauth2_clients;
pub mod organizations;
pub mod permissions;
pub mod pgp_keys;
pub mod platform;
pub mod privacy;
pub mod reactors;
pub mod resources;
pub mod roles;
pub mod scim_tokens;
pub mod scopes;
pub mod service_accounts;
pub mod settings;
pub mod tenants;
pub mod users;
pub mod webauthn_policy;
pub mod webhooks;

use crate::client::AxiamClient;

impl AxiamClient {
    /// The `organizations` management namespace.
    ///
    /// Organizations an SDK client may read and configure. Creation and deletion
    /// are outside the SDK boundary (§27.0).
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn organizations(&self) -> organizations::Organizations<'_> {
        organizations::Organizations::new(self)
    }

    /// The `tenants` management namespace.
    ///
    /// Tenants within an organization -- the isolation boundary every other
    /// namespace is scoped to.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn tenants(&self) -> tenants::Tenants<'_> {
        tenants::Tenants::new(self)
    }

    /// The `users` management namespace.
    ///
    /// Users within the client's tenant, and the administrative side of their
    /// second factor and lockout state.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn users(&self) -> users::Users<'_> {
        users::Users::new(self)
    }

    /// The `groups` management namespace.
    ///
    /// Named collections of users. Roles assigned to a group are inherited by
    /// every member.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn groups(&self) -> groups::Groups<'_> {
        groups::Groups::new(self)
    }

    /// The `roles` management namespace.
    ///
    /// Roles, their permission sets, and their assignment to users and groups.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn roles(&self) -> roles::Roles<'_> {
        roles::Roles::new(self)
    }

    /// The `permissions` management namespace.
    ///
    /// Permissions -- an action on a resource, optionally narrowed by a scope.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn permissions(&self) -> permissions::Permissions<'_> {
        permissions::Permissions::new(self)
    }

    /// The `resources` management namespace.
    ///
    /// The resource hierarchy role assignments cascade down.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn resources(&self) -> resources::Resources<'_> {
        resources::Resources::new(self)
    }

    /// The `scopes` management namespace.
    ///
    /// Sub-resource granularity, always addressed under their resource.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn scopes(&self) -> scopes::Scopes<'_> {
        scopes::Scopes::new(self)
    }

    /// The `service_accounts` management namespace.
    ///
    /// Machine identities, their secrets, and the certificate a device-bound one
    /// authenticates with.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn service_accounts(&self) -> service_accounts::ServiceAccounts<'_> {
        service_accounts::ServiceAccounts::new(self)
    }

    /// The `certificates` management namespace.
    ///
    /// End-entity X.509 certificates -- the ones issued to users, services and
    /// IoT devices.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn certificates(&self) -> certificates::Certificates<'_> {
        certificates::Certificates::new(self)
    }

    /// The `ca_certificates` management namespace.
    ///
    /// Organization CAs and the per-tenant signing CAs chained beneath them.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn ca_certificates(&self) -> ca_certificates::CaCertificates<'_> {
        ca_certificates::CaCertificates::new(self)
    }

    /// The `pgp_keys` management namespace.
    ///
    /// OpenPGP keys used for audit signing and encrypted data export.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn pgp_keys(&self) -> pgp_keys::PgpKeys<'_> {
        pgp_keys::PgpKeys::new(self)
    }

    /// The `webhooks` management namespace.
    ///
    /// Outbound event notifications. Delivery signatures are verified with the
    /// §13 helper, which this namespace configures.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn webhooks(&self) -> webhooks::Webhooks<'_> {
        webhooks::Webhooks::new(self)
    }

    /// The `oauth2_clients` management namespace.
    ///
    /// Registered OAuth2/OIDC clients -- the registration half of what §12, §21
    /// and §26 then speak to.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn oauth2_clients(&self) -> oauth2_clients::Oauth2Clients<'_> {
        oauth2_clients::Oauth2Clients::new(self)
    }

    /// The `federation` management namespace.
    ///
    /// Upstream IdP configuration and the per-user links it produces.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn federation(&self) -> federation::Federation<'_> {
        federation::Federation::new(self)
    }

    /// The `notification_rules` management namespace.
    ///
    /// Which events raise a notification, and to whom.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn notification_rules(&self) -> notification_rules::NotificationRules<'_> {
        notification_rules::NotificationRules::new(self)
    }

    /// The `email_config` management namespace.
    ///
    /// Transactional-mail transport, configurable at organization level and
    /// overridable per tenant.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn email_config(&self) -> email_config::EmailConfig<'_> {
        email_config::EmailConfig::new(self)
    }

    /// The `settings` management namespace.
    ///
    /// Effective settings, and the organization/tenant layers they resolve from.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn settings(&self) -> settings::Settings<'_> {
        settings::Settings::new(self)
    }

    /// The `scim_tokens` management namespace.
    ///
    /// Bearer tokens for the SCIM 2.0 provisioning endpoint.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn scim_tokens(&self) -> scim_tokens::ScimTokens<'_> {
        scim_tokens::ScimTokens::new(self)
    }

    /// The `reactors` management namespace.
    ///
    /// Registration of §22 AMQP extension actors -- the admin surface §22.9
    /// describes, which no SDK could previously reach.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn reactors(&self) -> reactors::Reactors<'_> {
        reactors::Reactors::new(self)
    }

    /// The `webauthn_policy` management namespace.
    ///
    /// Per-tenant attestation policy governing the §24 ceremonies, and the
    /// compliance report over it.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn webauthn_policy(&self) -> webauthn_policy::WebauthnPolicy<'_> {
        webauthn_policy::WebauthnPolicy::new(self)
    }

    /// The `audit` management namespace.
    ///
    /// Append-only audit log, read-only by construction.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn audit(&self) -> audit::Audit<'_> {
        audit::Audit::new(self)
    }

    /// The `privacy` management namespace.
    ///
    /// GDPR self-service: the authenticated account's own export and erasure.
    /// Scoped to the caller, never to another user.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn privacy(&self) -> privacy::Privacy<'_> {
        privacy::Privacy::new(self)
    }

    /// The `platform` management namespace.
    ///
    /// Deployment-level probes and FIDO metadata state. Unauthenticated where the
    /// server leaves them so.
    ///
    /// Acquiring the handle performs no I/O (§27.2 rule 1).
    #[must_use]
    pub fn platform(&self) -> platform::Platform<'_> {
        platform::Platform::new(self)
    }
}
