// @generated by tools/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate
// with `tools/gen_management.py`; CI verifies the committed output is current.

//! The `notification_rules` management namespace (CONTRACT §27.1).
//!
//! Which events raise a notification, and to whom.

#![allow(clippy::too_many_arguments)]

use uuid::Uuid;

use crate::AxiamError;
use crate::client::AxiamClient;
use crate::management::models;
use crate::management::page::{Page, PageRequest, collect_pages};
use crate::management::request::{Call, Verb};
use crate::management::scope::Scope;

/// The `notification_rules` namespace handle.
///
/// Which events raise a notification, and to whom.
///
/// Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
/// 1); it borrows the client and cannot outlive it.
#[derive(Clone, Copy)]
pub struct NotificationRules<'c> {
    pub(crate) client: &'c AxiamClient,
    pub(crate) scope: Scope,
}

impl std::fmt::Debug for NotificationRules<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("NotificationRules")
            .field("scope", &self.scope)
            .finish()
    }
}

impl<'c> NotificationRules<'c> {
    pub(crate) fn new(client: &'c AxiamClient) -> Self {
        Self {
            client,
            scope: Scope::default(),
        }
    }

    /// `GET /api/v1/notification-rules`
    pub async fn list(
        &self,
        page: PageRequest,
    ) -> Result<Page<models::NotificationRuleResponse>, AxiamError> {
        let query = page.query();
        let call = Call {
            operation: "notification_rules.list",
            verb: Verb::Get,
            path_template: "/api/v1/notification-rules",
            path: "/api/v1/notification-rules".to_string(),
            query: &query,
        };
        self.client
            .management_send::<_, Page<models::NotificationRuleResponse>>(call, None::<&()>)
            .await
    }

    /// Walk `notification_rules.list` to exhaustion, concatenating every page.
    ///
    /// The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
    /// if `total` disagrees, so a misreporting server costs one wasted request
    /// rather than an unbounded loop.
    pub async fn list_all(
        &self,
        start: PageRequest,
    ) -> Result<Vec<models::NotificationRuleResponse>, AxiamError> {
        collect_pages(start, |p| self.list(p)).await
    }

    /// `POST /api/v1/notification-rules`
    /// Not retried on failure (§27.4 rule 8): every write on this surface is
    /// issued exactly once, including the ones that look idempotent.
    pub async fn create(
        &self,
        body: &models::CreateNotificationRuleRequest,
    ) -> Result<models::NotificationRuleResponse, AxiamError> {
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "notification_rules.create",
            verb: Verb::Post,
            path_template: "/api/v1/notification-rules",
            path: "/api/v1/notification-rules".to_string(),
            query: &query,
        };
        self.client
            .management_send::<_, models::NotificationRuleResponse>(call, Some(body))
            .await
    }

    /// `GET /api/v1/notification-rules/{id}`
    pub async fn get(&self, id: Uuid) -> Result<models::NotificationRuleResponse, AxiamError> {
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "notification_rules.get",
            verb: Verb::Get,
            path_template: "/api/v1/notification-rules/{id}",
            path: format!("/api/v1/notification-rules/{id}"),
            query: &query,
        };
        self.client
            .management_send::<_, models::NotificationRuleResponse>(call, None::<&()>)
            .await
    }

    /// `PUT /api/v1/notification-rules/{id}`
    /// Not retried on failure (§27.4 rule 8): every write on this surface is
    /// issued exactly once, including the ones that look idempotent.
    pub async fn update(
        &self,
        id: Uuid,
        body: &models::UpdateNotificationRuleRequest,
    ) -> Result<models::NotificationRuleResponse, AxiamError> {
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "notification_rules.update",
            verb: Verb::Put,
            path_template: "/api/v1/notification-rules/{id}",
            path: format!("/api/v1/notification-rules/{id}"),
            query: &query,
        };
        self.client
            .management_send::<_, models::NotificationRuleResponse>(call, Some(body))
            .await
    }

    /// `DELETE /api/v1/notification-rules/{id}`
    /// Not retried on failure (§27.4 rule 8): every write on this surface is
    /// issued exactly once, including the ones that look idempotent.
    pub async fn delete(&self, id: Uuid) -> Result<(), AxiamError> {
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "notification_rules.delete",
            verb: Verb::Delete,
            path_template: "/api/v1/notification-rules/{id}",
            path: format!("/api/v1/notification-rules/{id}"),
            query: &query,
        };
        self.client
            .management_send_no_content(call, None::<&()>)
            .await
    }
}
