// @generated by tools/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate
// with `tools/gen_management.py`; CI verifies the committed output is current.

//! The `organizations` management namespace (CONTRACT §27.1).
//!
//! Organizations an SDK client may read and configure. Creation and deletion
//! are outside the SDK boundary (§27.0).

#![allow(clippy::too_many_arguments)]

use uuid::Uuid;

use crate::AxiamError;
use crate::client::AxiamClient;
use crate::management::models;
use crate::management::page::{Page, PageRequest, collect_pages};
use crate::management::request::{Call, Verb};
use crate::management::scope::Scope;

/// The `organizations` namespace handle.
///
/// Organizations an SDK client may read and configure. Creation and deletion
/// are outside the SDK boundary (§27.0).
///
/// Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
/// 1); it borrows the client and cannot outlive it.
#[derive(Clone, Copy)]
pub struct Organizations<'c> {
    pub(crate) client: &'c AxiamClient,
    pub(crate) scope: Scope,
}

impl std::fmt::Debug for Organizations<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Organizations")
            .field("scope", &self.scope)
            .finish()
    }
}

impl<'c> Organizations<'c> {
    pub(crate) fn new(client: &'c AxiamClient) -> Self {
        Self {
            client,
            scope: Scope::default(),
        }
    }

    /// Address a different organization than the client's own.
    ///
    /// §27.4 rule 3: the client's `org_id` is the default, and a platform-admin
    /// token legitimately overrides it.
    #[must_use]
    pub fn in_org(mut self, org_id: Uuid) -> Self {
        self.scope.org_id = Some(org_id);
        self
    }

    /// `GET /api/v1/organizations`
    pub async fn list(&self, page: PageRequest) -> Result<Page<models::Organization>, AxiamError> {
        let query = page.query();
        let call = Call {
            operation: "organizations.list",
            verb: Verb::Get,
            path_template: "/api/v1/organizations",
            path: "/api/v1/organizations".to_string(),
            query: &query,
        };
        self.client
            .management_send::<_, Page<models::Organization>>(call, None::<&()>)
            .await
    }

    /// Walk `organizations.list` to exhaustion, concatenating every page.
    ///
    /// The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
    /// if `total` disagrees, so a misreporting server costs one wasted request
    /// rather than an unbounded loop.
    pub async fn list_all(
        &self,
        start: PageRequest,
    ) -> Result<Vec<models::Organization>, AxiamError> {
        collect_pages(start, |p| self.list(p)).await
    }

    /// `GET /api/v1/organizations/{org_id}`
    pub async fn get(&self) -> Result<models::Organization, AxiamError> {
        let org_id = self.scope.org(self.client, "organizations.get")?;
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "organizations.get",
            verb: Verb::Get,
            path_template: "/api/v1/organizations/{org_id}",
            path: format!("/api/v1/organizations/{org_id}"),
            query: &query,
        };
        self.client
            .management_send::<_, models::Organization>(call, None::<&()>)
            .await
    }

    /// `PUT /api/v1/organizations/{org_id}`
    /// Not retried on failure (§27.4 rule 8): every write on this surface is
    /// issued exactly once, including the ones that look idempotent.
    pub async fn update(
        &self,
        body: &models::UpdateOrganizationRequest,
    ) -> Result<models::Organization, AxiamError> {
        let org_id = self.scope.org(self.client, "organizations.update")?;
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "organizations.update",
            verb: Verb::Put,
            path_template: "/api/v1/organizations/{org_id}",
            path: format!("/api/v1/organizations/{org_id}"),
            query: &query,
        };
        self.client
            .management_send::<_, models::Organization>(call, Some(body))
            .await
    }
}
