// @generated by tools/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate
// with `tools/gen_management.py`; CI verifies the committed output is current.

//! The `permissions` management namespace (CONTRACT §27.1).
//!
//! Permissions -- an action on a resource, optionally narrowed by a scope.

#![allow(clippy::too_many_arguments)]

use uuid::Uuid;

use crate::AxiamError;
use crate::client::AxiamClient;
use crate::management::models;
use crate::management::page::{Page, PageRequest, collect_pages};
use crate::management::request::{Call, Verb};
use crate::management::scope::Scope;

/// The `permissions` namespace handle.
///
/// Permissions -- an action on a resource, optionally narrowed by a scope.
///
/// Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
/// 1); it borrows the client and cannot outlive it.
#[derive(Clone, Copy)]
pub struct Permissions<'c> {
    pub(crate) client: &'c AxiamClient,
    pub(crate) scope: Scope,
}

impl std::fmt::Debug for Permissions<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Permissions")
            .field("scope", &self.scope)
            .finish()
    }
}

impl<'c> Permissions<'c> {
    pub(crate) fn new(client: &'c AxiamClient) -> Self {
        Self {
            client,
            scope: Scope::default(),
        }
    }

    /// `GET /api/v1/permissions`
    pub async fn list(&self, page: PageRequest) -> Result<Page<models::Permission>, AxiamError> {
        let query = page.query();
        let call = Call {
            operation: "permissions.list",
            verb: Verb::Get,
            path_template: "/api/v1/permissions",
            path: "/api/v1/permissions".to_string(),
            query: &query,
        };
        self.client
            .management_send::<_, Page<models::Permission>>(call, None::<&()>)
            .await
    }

    /// Walk `permissions.list` to exhaustion, concatenating every page.
    ///
    /// The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
    /// if `total` disagrees, so a misreporting server costs one wasted request
    /// rather than an unbounded loop.
    pub async fn list_all(
        &self,
        start: PageRequest,
    ) -> Result<Vec<models::Permission>, AxiamError> {
        collect_pages(start, |p| self.list(p)).await
    }

    /// `POST /api/v1/permissions`
    /// Not retried on failure (§27.4 rule 8): every write on this surface is
    /// issued exactly once, including the ones that look idempotent.
    pub async fn create(
        &self,
        body: &models::CreatePermissionRequest,
    ) -> Result<models::Permission, AxiamError> {
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "permissions.create",
            verb: Verb::Post,
            path_template: "/api/v1/permissions",
            path: "/api/v1/permissions".to_string(),
            query: &query,
        };
        self.client
            .management_send::<_, models::Permission>(call, Some(body))
            .await
    }

    /// `GET /api/v1/permissions/{permission_id}`
    pub async fn get(&self, permission_id: Uuid) -> Result<models::Permission, AxiamError> {
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "permissions.get",
            verb: Verb::Get,
            path_template: "/api/v1/permissions/{permission_id}",
            path: format!("/api/v1/permissions/{permission_id}"),
            query: &query,
        };
        self.client
            .management_send::<_, models::Permission>(call, None::<&()>)
            .await
    }

    /// `PUT /api/v1/permissions/{permission_id}`
    /// Not retried on failure (§27.4 rule 8): every write on this surface is
    /// issued exactly once, including the ones that look idempotent.
    pub async fn update(
        &self,
        permission_id: Uuid,
        body: &models::UpdatePermissionRequest,
    ) -> Result<models::Permission, AxiamError> {
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "permissions.update",
            verb: Verb::Put,
            path_template: "/api/v1/permissions/{permission_id}",
            path: format!("/api/v1/permissions/{permission_id}"),
            query: &query,
        };
        self.client
            .management_send::<_, models::Permission>(call, Some(body))
            .await
    }

    /// `DELETE /api/v1/permissions/{permission_id}`
    /// Not retried on failure (§27.4 rule 8): every write on this surface is
    /// issued exactly once, including the ones that look idempotent.
    pub async fn delete(&self, permission_id: Uuid) -> Result<(), AxiamError> {
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "permissions.delete",
            verb: Verb::Delete,
            path_template: "/api/v1/permissions/{permission_id}",
            path: format!("/api/v1/permissions/{permission_id}"),
            query: &query,
        };
        self.client
            .management_send_no_content(call, None::<&()>)
            .await
    }
}
