// @generated by tools/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate
// with `tools/gen_management.py`; CI verifies the committed output is current.

//! The `reactors` management namespace (CONTRACT §27.1).
//!
//! Registration of §22 AMQP extension actors -- the admin surface §22.9
//! describes, which no SDK could previously reach.

#![allow(clippy::too_many_arguments)]

use uuid::Uuid;

use crate::AxiamError;
use crate::client::AxiamClient;
use crate::management::models;
use crate::management::page::{Page, PageRequest, collect_pages};
use crate::management::request::{Call, Verb};
use crate::management::scope::Scope;

/// The `reactors` namespace handle.
///
/// Registration of §22 AMQP extension actors -- the admin surface §22.9
/// describes, which no SDK could previously reach.
///
/// Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
/// 1); it borrows the client and cannot outlive it.
#[derive(Clone, Copy)]
pub struct Reactors<'c> {
    pub(crate) client: &'c AxiamClient,
    pub(crate) scope: Scope,
}

impl std::fmt::Debug for Reactors<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Reactors")
            .field("scope", &self.scope)
            .finish()
    }
}

impl<'c> Reactors<'c> {
    pub(crate) fn new(client: &'c AxiamClient) -> Self {
        Self {
            client,
            scope: Scope::default(),
        }
    }

    /// `GET /api/v1/reactors`
    pub async fn list(
        &self,
        page: PageRequest,
    ) -> Result<Page<models::ReactorResponse>, AxiamError> {
        let query = page.query();
        let call = Call {
            operation: "reactors.list",
            verb: Verb::Get,
            path_template: "/api/v1/reactors",
            path: "/api/v1/reactors".to_string(),
            query: &query,
        };
        self.client
            .management_send::<_, Page<models::ReactorResponse>>(call, None::<&()>)
            .await
    }

    /// Walk `reactors.list` to exhaustion, concatenating every page.
    ///
    /// The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
    /// if `total` disagrees, so a misreporting server costs one wasted request
    /// rather than an unbounded loop.
    pub async fn list_all(
        &self,
        start: PageRequest,
    ) -> Result<Vec<models::ReactorResponse>, AxiamError> {
        collect_pages(start, |p| self.list(p)).await
    }

    /// `POST /api/v1/reactors`
    /// Not retried on failure (§27.4 rule 8): every write on this surface is
    /// issued exactly once, including the ones that look idempotent.
    pub async fn create(
        &self,
        body: &models::CreateReactorRequest,
    ) -> Result<models::ReactorResponse, AxiamError> {
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "reactors.create",
            verb: Verb::Post,
            path_template: "/api/v1/reactors",
            path: "/api/v1/reactors".to_string(),
            query: &query,
        };
        self.client
            .management_send::<_, models::ReactorResponse>(call, Some(body))
            .await
    }

    /// `GET /api/v1/reactors/{id}`
    pub async fn get(&self, id: Uuid) -> Result<models::ReactorResponse, AxiamError> {
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "reactors.get",
            verb: Verb::Get,
            path_template: "/api/v1/reactors/{id}",
            path: format!("/api/v1/reactors/{id}"),
            query: &query,
        };
        self.client
            .management_send::<_, models::ReactorResponse>(call, None::<&()>)
            .await
    }

    /// `PUT /api/v1/reactors/{id}`
    /// Not retried on failure (§27.4 rule 8): every write on this surface is
    /// issued exactly once, including the ones that look idempotent.
    pub async fn update(
        &self,
        id: Uuid,
        body: &models::UpdateReactorRequest,
    ) -> Result<models::ReactorResponse, AxiamError> {
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "reactors.update",
            verb: Verb::Put,
            path_template: "/api/v1/reactors/{id}",
            path: format!("/api/v1/reactors/{id}"),
            query: &query,
        };
        self.client
            .management_send::<_, models::ReactorResponse>(call, Some(body))
            .await
    }

    /// `DELETE /api/v1/reactors/{id}`
    /// Not retried on failure (§27.4 rule 8): every write on this surface is
    /// issued exactly once, including the ones that look idempotent.
    pub async fn delete(&self, id: Uuid) -> Result<(), AxiamError> {
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "reactors.delete",
            verb: Verb::Delete,
            path_template: "/api/v1/reactors/{id}",
            path: format!("/api/v1/reactors/{id}"),
            query: &query,
        };
        self.client
            .management_send_no_content(call, None::<&()>)
            .await
    }

    /// `GET /api/v1/reactors/events`
    pub async fn list_events(&self) -> Result<Vec<models::ReactorEventDescriptor>, AxiamError> {
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "reactors.list_events",
            verb: Verb::Get,
            path_template: "/api/v1/reactors/events",
            path: "/api/v1/reactors/events".to_string(),
            query: &query,
        };
        self.client
            .management_send::<_, Vec<models::ReactorEventDescriptor>>(call, None::<&()>)
            .await
    }
}
