// @generated by tools/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate
// with `tools/gen_management.py`; CI verifies the committed output is current.

//! The `webhooks` management namespace (CONTRACT §27.1).
//!
//! Outbound event notifications. Delivery signatures are verified with the
//! §13 helper, which this namespace configures.

#![allow(clippy::too_many_arguments)]

use uuid::Uuid;

use crate::AxiamError;
use crate::client::AxiamClient;
use crate::management::models;
use crate::management::page::{Page, PageRequest, collect_pages};
use crate::management::request::{Call, Verb};
use crate::management::scope::Scope;

/// The `webhooks` namespace handle.
///
/// Outbound event notifications. Delivery signatures are verified with the
/// §13 helper, which this namespace configures.
///
/// Acquiring one performs no I/O and allocates nothing meaningful (§27.2 rule
/// 1); it borrows the client and cannot outlive it.
#[derive(Clone, Copy)]
pub struct Webhooks<'c> {
    pub(crate) client: &'c AxiamClient,
    pub(crate) scope: Scope,
}

impl std::fmt::Debug for Webhooks<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Webhooks")
            .field("scope", &self.scope)
            .finish()
    }
}

impl<'c> Webhooks<'c> {
    pub(crate) fn new(client: &'c AxiamClient) -> Self {
        Self {
            client,
            scope: Scope::default(),
        }
    }

    /// `GET /api/v1/webhooks`
    pub async fn list(
        &self,
        page: PageRequest,
    ) -> Result<Page<models::WebhookResponse>, AxiamError> {
        let query = page.query();
        let call = Call {
            operation: "webhooks.list",
            verb: Verb::Get,
            path_template: "/api/v1/webhooks",
            path: "/api/v1/webhooks".to_string(),
            query: &query,
        };
        self.client
            .management_send::<_, Page<models::WebhookResponse>>(call, None::<&()>)
            .await
    }

    /// Walk `webhooks.list` to exhaustion, concatenating every page.
    ///
    /// The auto-paging form §27.4 rule 4 requires. It stops on an empty page even
    /// if `total` disagrees, so a misreporting server costs one wasted request
    /// rather than an unbounded loop.
    pub async fn list_all(
        &self,
        start: PageRequest,
    ) -> Result<Vec<models::WebhookResponse>, AxiamError> {
        collect_pages(start, |p| self.list(p)).await
    }

    /// `POST /api/v1/webhooks`
    /// Not retried on failure (§27.4 rule 8): every write on this surface is
    /// issued exactly once, including the ones that look idempotent.
    pub async fn create(
        &self,
        body: &models::CreateWebhookRequest,
    ) -> Result<models::WebhookResponse, AxiamError> {
        let body = models::CreateWebhookRequestWire::from(body);
        let body = &body;
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "webhooks.create",
            verb: Verb::Post,
            path_template: "/api/v1/webhooks",
            path: "/api/v1/webhooks".to_string(),
            query: &query,
        };
        self.client
            .management_send::<_, models::WebhookResponse>(call, Some(body))
            .await
    }

    /// `GET /api/v1/webhooks/{id}`
    pub async fn get(&self, id: Uuid) -> Result<models::WebhookResponse, AxiamError> {
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "webhooks.get",
            verb: Verb::Get,
            path_template: "/api/v1/webhooks/{id}",
            path: format!("/api/v1/webhooks/{id}"),
            query: &query,
        };
        self.client
            .management_send::<_, models::WebhookResponse>(call, None::<&()>)
            .await
    }

    /// `PUT /api/v1/webhooks/{id}`
    /// Not retried on failure (§27.4 rule 8): every write on this surface is
    /// issued exactly once, including the ones that look idempotent.
    pub async fn update(
        &self,
        id: Uuid,
        body: &models::UpdateWebhookRequest,
    ) -> Result<models::WebhookResponse, AxiamError> {
        let body = models::UpdateWebhookRequestWire::from(body);
        let body = &body;
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "webhooks.update",
            verb: Verb::Put,
            path_template: "/api/v1/webhooks/{id}",
            path: format!("/api/v1/webhooks/{id}"),
            query: &query,
        };
        self.client
            .management_send::<_, models::WebhookResponse>(call, Some(body))
            .await
    }

    /// `DELETE /api/v1/webhooks/{id}`
    /// Not retried on failure (§27.4 rule 8): every write on this surface is
    /// issued exactly once, including the ones that look idempotent.
    pub async fn delete(&self, id: Uuid) -> Result<(), AxiamError> {
        let query: Vec<(&'static str, String)> = Vec::new();
        let call = Call {
            operation: "webhooks.delete",
            verb: Verb::Delete,
            path_template: "/api/v1/webhooks/{id}",
            path: format!("/api/v1/webhooks/{id}"),
            query: &query,
        };
        self.client
            .management_send_no_content(call, None::<&()>)
            .await
    }
}
