#!/usr/bin/env python3
"""Generate the CONTRACT §27 management surface for the Rust SDK.

Reads the two vendored artifacts -- ``management-registry.json`` (the
normative §27 vocabulary) and ``openapi.json`` (the schemas it refers to) --
and writes:

    src/management/models.rs                  the request/response types
    src/management/ops/<namespace>.rs         one handle per namespace
    src/management/ops/mod.rs
    tests/management_surface_generated.rs     one wire assertion per operation

§27.8 draws the line this script works to: the models and the raw calls are
generated, everything ergonomic is not. Nothing here opens a connection or
maps an error -- every generated call funnels into
``AxiamClient::management_send``, so §3, §4, §5, §6, §9, §16 and §19 are
inherited rather than reimplemented 146 times.

The generated test matters as much as the generated code. The SDK's coverage
floor is 90% of lines, and 146 hand-written smoke tests is the kind of chore
that gets half-done; generating them from the same registry means a new
operation arrives with its own coverage or not at all.

Usage:
    tools/gen_management.py            # write
    tools/gen_management.py --check    # verify committed output is current
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "management-registry.json"
OPENAPI = ROOT / "openapi.json"
MODELS_OUT = ROOT / "src" / "management" / "models.rs"
OPS_DIR = ROOT / "src" / "management" / "ops"
TEST_OUT = ROOT / "tests" / "management_surface_generated.rs"

BANNER = """// @generated by tools/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate
// with `tools/gen_management.py`; CI verifies the committed output is current.
"""

RUST_KEYWORDS = {
    "as", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern",
    "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod",
    "move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct",
    "super", "trait", "true", "type", "unsafe", "use", "where", "while", "async",
    "await", "abstract", "become", "box", "do", "final", "macro", "override",
    "priv", "typeof", "unsized", "virtual", "yield", "try", "union",
}

# §27.4 rule 3: `{org_id}` always defaults from the client. `{tenant_id}`
# defaults from the client only where it names the *context*; in `tenants` and
# in the signing-CA routes it names the object being acted on, so it stays an
# ordinary argument.
IMPLICIT_TENANT_NAMESPACES = {"email_config", "settings", "webauthn_policy"}


# ---------------------------------------------------------------------------
# Naming
# ---------------------------------------------------------------------------

def pascal(name: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[_\-\s]+", name) if p)


def field_name(name: str) -> tuple[str, str | None]:
    """Rust field name plus the ``serde(rename)`` it needs, if any."""
    ident = name
    if ident in RUST_KEYWORDS:
        return f"r#{ident}", None
    if not re.fullmatch(r"[a-z_][a-z0-9_]*", ident):
        safe = re.sub(r"[^a-z0-9_]", "_", ident.lower())
        return safe, name
    return ident, None


def wrap_doc(text: str, width: int = 74) -> list[str]:
    """Reflow a paragraph to `width`, preserving blank lines.

    rustfmt does not reflow comments, so without this every generated doc
    comment is one 400-column line and the files are unreadable in review.
    """
    import textwrap

    out: list[str] = []
    for para in text.strip().split("\n\n"):
        collapsed = " ".join(para.split())
        if not collapsed:
            out.append("")
            continue
        out.extend(textwrap.wrap(collapsed, width=width) or [""])
        out.append("")
    while out and out[-1] == "":
        out.pop()
    return out


def doc_lines(text: str | None, indent: str = "") -> list[str]:
    """Render an OpenAPI description as Rust doc comments.

    Every generated public item gets one: the crate is `#![warn(missing_docs)]`
    and a generated file that trips it teaches everyone to ignore the lint.
    """
    if not text:
        return []
    out = []
    for raw in wrap_doc(text):
        line = raw.rstrip().replace("\t", "    ")
        # `[` starts an intra-doc link in rustdoc; a stray one from a server
        # doc comment becomes a broken-link warning under `cargo doc`.
        line = line.replace("[", "\\[").replace("]", "\\]")
        out.append(f"{indent}/// {line}".rstrip())
    return out


# ---------------------------------------------------------------------------
# Type mapping
# ---------------------------------------------------------------------------

#: Rust types the generator emits or uses that implement `Copy`. Cloning one
#: is what `clippy::clone_on_copy` fires on, and the generated wire conversions
#: would otherwise do it fifteen times for `Uuid` alone.
COPY_PRIMITIVES = {"Uuid", "bool", "i32", "i64", "f64", "u32", "u64"}


class Types:
    def __init__(self, spec: dict[str, Any]) -> None:
        self.spec = spec
        self.schemas = spec["components"]["schemas"]
        #: Structs synthesized for anonymous `oneOf` variants, name -> schema.
        self.synthetic: dict[str, dict[str, Any]] = {}
        #: Every string-enum schema; all of them are emitted `Copy`.
        self.copy_enums = {
            pascal(n) for n, sc in self.schemas.items() if "enum" in sc
        }

    def is_copy(self, ty: str) -> bool:
        """Whether a generated Rust type is `Copy`, `Option` unwrapped."""
        if ty.startswith("Option<") and ty.endswith(">"):
            return self.is_copy(ty[len("Option<"):-1])
        return ty in COPY_PRIMITIVES or ty in self.copy_enums

    def resolve(self, schema: dict[str, Any]) -> dict[str, Any]:
        while "$ref" in schema:
            schema = self.schemas[schema["$ref"].rsplit("/", 1)[-1]]
        return schema

    @staticmethod
    def nullable_ref(schema: dict[str, Any]) -> str | None:
        """`{oneOf: [{type: null}, {$ref: X}]}` -- utoipa's `Option<X>`."""
        variants = schema.get("oneOf")
        if not variants or len(variants) != 2:
            return None
        nulls = [v for v in variants if v.get("type") == "null"]
        refs = [v for v in variants if "$ref" in v]
        if len(nulls) == 1 and len(refs) == 1:
            return refs[0]["$ref"].rsplit("/", 1)[-1]
        return None

    def rust(self, schema: dict[str, Any]) -> str:
        """The Rust type for a property schema, `Option<..>` included."""
        if "$ref" in schema:
            return pascal(schema["$ref"].rsplit("/", 1)[-1])
        inner = self.nullable_ref(schema)
        if inner:
            return f"Option<{pascal(inner)}>"
        if "oneOf" in schema or "anyOf" in schema:
            return "serde_json::Value"
        if not schema:
            return "serde_json::Value"

        t = schema.get("type")
        optional = False
        if isinstance(t, list):
            optional = "null" in t
            rest = [x for x in t if x != "null"]
            t = rest[0] if rest else None
            schema = {k: v for k, v in schema.items() if k != "type"}
            schema["type"] = t

        base: str
        if t == "string":
            fmt = schema.get("format")
            if fmt == "uuid":
                base = "Uuid"
            else:
                # `date-time` maps to String on purpose: `chrono` is an
                # optional dependency of this crate, and making 60 timestamp
                # fields require it would turn a feature flag into a hard one.
                base = "String"
        elif t == "integer":
            base = {"int32": "i32", "int64": "i64"}.get(schema.get("format", ""), "i64")
        elif t == "number":
            base = "f64"
        elif t == "boolean":
            base = "bool"
        elif t == "array":
            base = f"Vec<{self.rust(schema.get('items', {}))}>"
        elif t == "object":
            base = "serde_json::Value"
        else:
            base = "serde_json::Value"
        return f"Option<{base}>" if optional else base

    def flatten(self, name: str) -> tuple[dict[str, Any], set[str], str | None]:
        """Properties + required set of a schema, `allOf` composition resolved."""
        schema = self.schemas[name]
        props: dict[str, Any] = {}
        required: set[str] = set()
        desc = schema.get("description")

        def absorb(node: dict[str, Any]) -> None:
            node = self.resolve(node) if "$ref" in node else node
            props.update(node.get("properties", {}))
            required.update(node.get("required", []))
            for sub in node.get("allOf", []):
                absorb(sub)

        absorb(schema)
        return props, required, desc


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

def closure(reg: dict[str, Any], types: Types) -> list[str]:
    seeds: set[str] = set()
    for ns in reg["namespaces"].values():
        for op in ns["operations"].values():
            if op["request_schema"]:
                seeds.add(op["request_schema"].lstrip("[]"))
            if op["response"]["schema"]:
                seeds.add(op["response"]["schema"].lstrip("[]"))

    def refs_in(node: Any, out: set[str]) -> None:
        if isinstance(node, dict):
            if "$ref" in node:
                out.add(node["$ref"].rsplit("/", 1)[-1])
            for v in node.values():
                refs_in(v, out)
        elif isinstance(node, list):
            for v in node:
                refs_in(v, out)

    seen: set[str] = set()
    frontier = set(seeds)
    while frontier:
        n = frontier.pop()
        if n in seen or n not in types.schemas:
            continue
        seen.add(n)
        found: set[str] = set()
        refs_in(types.schemas[n], found)
        frontier |= found - seen
    return sorted(seen)


def wire_directions(reg: dict[str, Any]) -> dict[str, set[str]]:
    """schema name -> {"request"} / {"response"} / both.

    A secret-carrying type needs a wire twin, but only in the direction it
    actually travels: a request body needs `From<&Public> for Wire`, a response
    needs `From<Wire> for Public`. Emitting both leaves half of them dead --
    which is fifty uncovered lines in a repo whose coverage floor is 90%, for
    conversions nothing can ever call.
    """
    out: dict[str, set[str]] = {}
    for ns in reg["namespaces"].values():
        for op in ns["operations"].values():
            if op["request_schema"] and op["sensitive_request_fields"]:
                out.setdefault(op["request_schema"].lstrip("[]"), set()).add("request")
            if op["response"]["schema"] and op["sensitive_response_fields"]:
                out.setdefault(op["response"]["schema"].lstrip("[]"), set()).add("response")
    return out


def sensitive_map(reg: dict[str, Any]) -> dict[str, set[str]]:
    """schema name -> the fields §27.5 requires wrapped."""
    out: dict[str, set[str]] = {}
    for ns in reg["namespaces"].values():
        for op in ns["operations"].values():
            if op["request_schema"] and op["sensitive_request_fields"]:
                out.setdefault(op["request_schema"].lstrip("[]"), set()).update(
                    op["sensitive_request_fields"]
                )
            if op["response"]["schema"] and op["sensitive_response_fields"]:
                out.setdefault(op["response"]["schema"].lstrip("[]"), set()).update(
                    op["sensitive_response_fields"]
                )
    return out


def discriminated(schema: dict[str, Any], types: Types) -> list[tuple[str, str, dict]] | None:
    """Detect an internally-tagged union: `oneOf` where each arm pins one tag value.

    Both unions on this surface have that shape (`ProviderConfig` tags on
    `kind`, `MdsRefreshOutcome` on `outcome`), and both are lossy as
    `serde_json::Value` -- which is what a generator that gives up here emits.
    Returns `(tag_field, [(tag_value, payload_schema)])` or `None`.
    """
    variants = schema.get("oneOf")
    if not variants or len(variants) < 2:
        return None
    tag_field: str | None = None
    arms: list[tuple[str, dict[str, Any]]] = []
    for variant in variants:
        parts = variant.get("allOf", [variant])
        tag: tuple[str, str] | None = None
        payload: dict[str, Any] | None = None
        leftovers: dict[str, Any] = {"type": "object", "properties": {}, "required": []}
        for part in parts:
            if "$ref" in part:
                payload = part
                continue
            props = part.get("properties", {})
            for name, prop in props.items():
                values = prop.get("enum")
                if prop.get("type") == "string" and isinstance(values, list) and len(values) == 1:
                    tag = (name, values[0])
                else:
                    leftovers["properties"][name] = prop
                    if name in part.get("required", []):
                        leftovers["required"].append(name)
        if tag is None:
            return None
        if tag_field is None:
            tag_field = tag[0]
        elif tag_field != tag[0]:
            return None
        arms.append((tag[1], payload if payload is not None else leftovers))
    return [(tag_field, value, payload) for value, payload in arms]  # type: ignore[misc]


def emit_models(reg: dict[str, Any], types: Types) -> str:
    names = closure(reg, types)
    secrets = sensitive_map(reg)
    directions = wire_directions(reg)
    out: list[str] = [BANNER, """
//! Request and response types for the CONTRACT §27 management surface.
//!
//! Every type here is derived from a schema in `openapi.json`, reached from
//! the operations `management-registry.json` names. Three shapes recur and are
//! worth knowing before reading:
//!
//! * **Sparse update bodies.** Every field is `Option` and every field is
//!   skipped when `None`, so a body carrying one field changes one field
//!   (§27.4 rule 5). They derive [`Default`], which is what makes
//!   `UpdateUserRequest { email: Some(..), ..Default::default() }` the natural
//!   way to write one. A field that is `None` is *absent from the wire body*,
//!   not sent as `null` -- this SDK cannot express "set this field to null",
//!   which is the safe direction to be inexpressive in.
//! * **Replacement bodies.** `SetOrgSettings`, `EmailConfigOverride`'s org
//!   twin, `WebauthnAttestationPolicy` and `SetMtlsTrustAnchor` have required
//!   fields, because a `PUT` on those routes replaces rather than patches.
//!   The compiler makes you supply all of them, which is the point.
//! * **Types carrying a secret.** These are a public type holding
//!   [`Sensitive<T>`](crate::Sensitive) plus a private wire twin, because §7
//!   forbids `Sensitive` from deriving `Serialize`/`Deserialize` at all -- a
//!   derive on the wrapper would route straight around its redacting `Debug`.

#![allow(clippy::struct_excessive_bools)]

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::Sensitive;
"""]

    for name in names:
        schema = types.schemas[name]
        rname = pascal(name)
        if "enum" in schema:
            out.append(emit_enum(rname, schema))
            continue
        union = discriminated(schema, types)
        if union:
            out.append(emit_union(rname, schema, union, types))
            continue
        out.append(
            emit_struct(rname, name, types, secrets.get(name, set()), directions.get(name, set()))
        )
    return "\n".join(out)


def emit_enum(rname: str, schema: dict[str, Any]) -> str:
    lines = doc_lines(schema.get("description") or f"`{rname}` (generated from openapi.json).")
    lines.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]")
    lines.append("#[non_exhaustive]")
    lines.append(f"pub enum {rname} {{")
    for value in schema["enum"]:
        variant = pascal(str(value))
        lines.extend(doc_lines(f"`{value}`", "    "))
        if variant != value:
            lines.append(f'    #[serde(rename = "{value}")]')
        lines.append(f"    {variant},")
    lines.append("}\n")
    return "\n".join(lines)


def emit_union(rname: str, schema: dict[str, Any], arms: list, types: Types) -> str:
    tag_field = arms[0][0]
    lines = doc_lines(
        schema.get("description")
        or f"`{rname}` -- an internally-tagged union discriminated by `{tag_field}`."
    )
    lines.append("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]")
    lines.append(f'#[serde(tag = "{tag_field}")]')
    lines.append("#[non_exhaustive]")
    lines.append(f"pub enum {rname} {{")
    extra: list[str] = []
    for _, value, payload in arms:
        variant = pascal(str(value))
        lines.extend(doc_lines(f"`{tag_field} = \"{value}\"`", "    "))
        if variant != value:
            lines.append(f'    #[serde(rename = "{value}")]')
        if "$ref" in payload:
            # An `allOf[$ref, {tag}]` arm: the payload is a named struct, and
            # serde flattens a newtype variant under an internal tag.
            lines.append(f"    {variant}({pascal(payload['$ref'].rsplit('/', 1)[-1])}),")
        else:
            # An anonymous arm: synthesize a struct variant inline rather than
            # falling back to `serde_json::Value` and losing the shape.
            lines.append(f"    {variant} {{")
            required = set(payload.get("required", []))
            for pname, pschema in sorted(payload.get("properties", {}).items()):
                ident, rename = field_name(pname)
                ty = types.rust(pschema)
                if pname not in required and not ty.startswith("Option<"):
                    ty = f"Option<{ty}>"
                lines.extend(doc_lines(pschema.get("description") or f"`{pname}`.", "        "))
                if rename:
                    lines.append(f'        #[serde(rename = "{rename}")]')
                if ty.startswith("Option<"):
                    lines.append('        #[serde(default, skip_serializing_if = "Option::is_none")]')
                lines.append(f"        {ident}: {ty},")
            lines.append("    },")
    lines.append("}\n")
    lines.extend(extra)
    return "\n".join(lines)


def emit_struct(
    rname: str, name: str, types: Types, secrets: set[str], directions: set[str]
) -> str:
    props, required, desc = types.flatten(name)
    fields: list[tuple[str, str | None, str, bool, str | None]] = []
    for pname, pschema in sorted(props.items()):
        ident, rename = field_name(pname)
        if pname in secrets:
            # §7: `Sensitive` derives neither `Serialize` nor `Deserialize`, so
            # a struct holding one cannot derive them either. That is why these
            # types get a wire twin below rather than an attribute.
            ty = "Sensitive<String>"
            if pname not in required:
                ty = f"Option<{ty}>"
        else:
            ty = types.rust(pschema)
            if pname not in required and not ty.startswith("Option<"):
                ty = f"Option<{ty}>"
        fields.append((ident, rename, ty, pname in secrets, pschema.get("description")))

    all_optional = all(ty.startswith("Option<") for _, _, ty, _, _ in fields)
    lines = doc_lines(desc or f"`{rname}` (generated from openapi.json).")
    if all_optional and fields:
        lines.extend(doc_lines(
            "\nEvery field is optional, so this is a **sparse** body: what you "
            "leave `None` is left unchanged, and is omitted from the wire "
            "request entirely rather than sent as `null` (§27.4 rule 5). "
            "Construct it with `..Default::default()`."
        ))

    if secrets:
        return emit_sensitive_struct(rname, lines, fields, all_optional, types, directions)

    derives = ["Debug", "Clone", "PartialEq", "Serialize", "Deserialize"]
    if all_optional:
        derives.insert(3, "Default")
    lines.append(f"#[derive({', '.join(derives)})]")
    lines.append(f"pub struct {rname} {{")
    if not fields:
        lines.append("    // The server documents no fields on this schema.")
    for ident, rename, ty, _, fdesc in fields:
        lines.extend(doc_lines(fdesc or f"`{ident}`.", "    "))
        if rename:
            lines.append(f'    #[serde(rename = "{rename}")]')
        if ty.startswith("Option<"):
            lines.append('    #[serde(default, skip_serializing_if = "Option::is_none")]')
        lines.append(f"    pub {ident}: {ty},")
    lines.append("}\n")
    return "\n".join(lines)


def emit_sensitive_struct(
    rname: str,
    lines: list[str],
    fields: list[tuple[str, str | None, str, bool, str | None]],
    all_optional: bool,
    types: Types,
    directions: set[str],
) -> str:
    """A public type holding `Sensitive<T>`, plus the wire twin that crosses the socket.

    §7 rule 1 forbids `Sensitive` from deriving either serde trait, so the
    public type cannot derive them either. Splitting the type is the pattern
    the SDK already uses for TOTP enrolment (`src/rest/account.rs`): the wire
    twin is private, holds plain `String`, and the two conversions below are
    the only places a secret is unwrapped or wrapped -- one greppable call each
    (§7 rule 4), rather than fourteen scattered ones.
    """
    lines.extend(doc_lines(
        "\nThis type carries secret material (§27.5), so the field is "
        "[`Sensitive`](crate::Sensitive) and the type derives neither "
        "`Serialize` nor `Deserialize`. Read the secret with `.expose()`, "
        "deliberately, at the point you need it."
    ))
    derives = ["Debug", "Clone"]
    if all_optional:
        derives.append("Default")
    out = list(lines)
    out.append(f"#[derive({', '.join(derives)})]")
    out.append(f"pub struct {rname} {{")
    for ident, _, ty, is_secret, fdesc in fields:
        out.extend(doc_lines(fdesc or f"`{ident}`.", "    "))
        if is_secret:
            # A blank `///` line, or rustdoc runs this into the paragraph above.
            out.append("    ///")
            out.extend(doc_lines(
                "**Secret.** Redacted from every debug and log rendering; "
                "call `.expose()` to read it.", "    "))
        out.append(f"    pub {ident}: {ty},")
    out.append("}\n")

    wire = f"{rname}Wire"
    out.append(f"/// Wire twin of [`{rname}`] -- plain strings, private, never logged.")
    wire_derives = ["Debug", "Clone", "Serialize", "Deserialize"]
    if all_optional:
        wire_derives.insert(2, "Default")
    out.append(f"#[derive({', '.join(wire_derives)})]")
    out.append(f"pub(crate) struct {wire} {{")
    for ident, rename, ty, is_secret, _ in fields:
        wty = ty.replace("Sensitive<String>", "String") if is_secret else ty
        if rename:
            out.append(f'    #[serde(rename = "{rename}")]')
        if wty.startswith("Option<"):
            out.append('    #[serde(default, skip_serializing_if = "Option::is_none")]')
        out.append(f"    pub(crate) {ident}: {wty},")
    out.append("}\n")

    if "response" in directions:
        out.append(f"impl From<{wire}> for {rname} {{")
        out.append(f"    fn from(w: {wire}) -> Self {{")
        out.append("        Self {")
        for ident, _, ty, is_secret, _ in fields:
            if not is_secret:
                out.append(f"            {ident}: w.{ident},")
            elif ty.startswith("Option<"):
                out.append(
                    f"            {ident}: w.{ident}.map(crate::management::error::wrap_from_wire),"
                )
            else:
                out.append(
                    f"            {ident}: crate::management::error::wrap_from_wire(w.{ident}),"
                )
        out.append("        }")
        out.append("    }")
        out.append("}\n")

    if "request" in directions:
        out.append(f"impl From<&{rname}> for {wire} {{")
        out.append(f"    fn from(v: &{rname}) -> Self {{")
        out.append("        Self {")
        for ident, _, ty, is_secret, _ in fields:
            if not is_secret:
                # `.clone()` on a `Copy` field is what `clone_on_copy` fires on.
                accessor = f"v.{ident}" if types.is_copy(ty) else f"v.{ident}.clone()"
                out.append(f"            {ident}: {accessor},")
            elif ty.startswith("Option<"):
                out.append(
                    f"            {ident}: v.{ident}.as_ref()"
                    ".map(crate::management::error::expose_for_wire),"
                )
            else:
                out.append(
                    f"            {ident}: crate::management::error::expose_for_wire(&v.{ident}),"
                )
        out.append("        }")
        out.append("    }")
        out.append("}\n")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Operations
# ---------------------------------------------------------------------------

def param_rust_type(fmt: str | None) -> str:
    return "Uuid" if fmt == "uuid" else "&str"


def query_rust_type(qtype: Any) -> str:
    if isinstance(qtype, list):
        qtype = next((t for t in qtype if t != "null"), "string")
    return {"integer": "i64", "boolean": "bool"}.get(qtype, "&str")


def implicit_params(namespace: str, op: dict[str, Any]) -> set[str]:
    names = {p["name"] for p in op["path_params"]}
    out: set[str] = set()
    if "org_id" in names:
        out.add("org_id")
    if "tenant_id" in names and namespace in IMPLICIT_TENANT_NAMESPACES:
        out.add("tenant_id")
    return out


def response_type(op: dict[str, Any], secrets: dict[str, set[str]]) -> tuple[str, str, str]:
    """`(public type, wire type, kind)` for an operation's success body.

    Model types are written `models::X` rather than glob-imported: the schema
    set genuinely contains a `Scope` and an `EmailConfig`, which would collide
    with the scope type and with the `email_config` handle.
    """
    resp = op["response"]
    kind = resp["kind"]
    if kind == "none":
        return "()", "()", "none"
    schema = resp["schema"]
    public = f"models::{pascal(schema)}"
    wire = f"models::{pascal(schema)}Wire" if schema in secrets else public
    if kind == "array":
        return f"Vec<{public}>", f"Vec<{wire}>", "array"
    if kind == "page":
        return f"Page<{public}>", f"Page<{wire}>", "page"
    return public, wire, "object"


def emit_namespace(
    namespace: str, nsdef: dict[str, Any], secrets: dict[str, set[str]], types: Types
) -> tuple[str, list[str]]:
    rname = pascal(namespace)
    ops = nsdef["operations"]
    has_org = any("org_id" in implicit_params(namespace, o) for o in ops.values())
    has_tenant = any("tenant_id" in implicit_params(namespace, o) for o in ops.values())

    lines = [BANNER]
    lines.append(f"//! The `{namespace}` management namespace (CONTRACT §27.1).")
    lines.append("//!")
    for line in wrap_doc(nsdef["doc"]):
        lines.append(f"//! {line}".rstrip())
    lines.append("")
    lines.append("#![allow(clippy::too_many_arguments)]")
    lines.append("")
    # Imports are emitted from what the body actually references. A fixed list
    # is simpler to write and produces `unused_imports` on the namespaces that
    # happen not to paginate -- and CI runs clippy with `-D warnings`.
    import_marker = "@@IMPORTS@@"
    lines.append(import_marker)

    lines.extend(doc_lines(
        f"The `{namespace}` namespace handle.\n\n{nsdef['doc']}\n\n"
        "Acquiring one performs no I/O and allocates nothing meaningful "
        "(§27.2 rule 1); it borrows the client and cannot outlive it."
    ))
    lines.append("#[derive(Clone, Copy)]")
    lines.append(f"pub struct {rname}<'c> {{")
    lines.append("    pub(crate) client: &'c AxiamClient,")
    lines.append("    pub(crate) scope: Scope,")
    lines.append("}")
    lines.append("")
    # A hand-rolled `Debug`: deriving it would require `AxiamClient: Debug`,
    # and a client that rendered itself would render its cookie jar.
    lines.append(f"impl std::fmt::Debug for {rname}<'_> {{")
    lines.append("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {")
    lines.append(f'        f.debug_struct("{rname}").field("scope", &self.scope).finish()')
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append(f"impl<'c> {rname}<'c> {{")
    lines.append("    pub(crate) fn new(client: &'c AxiamClient) -> Self {")
    lines.append("        Self { client, scope: Scope::default() }")
    lines.append("    }")
    lines.append("")
    if has_org:
        lines.extend(doc_lines(
            "Address a different organization than the client's own.\n\n"
            "§27.4 rule 3: the client's `org_id` is the default, and a "
            "platform-admin token legitimately overrides it.", "    "))
        lines.append("    #[must_use]")
        lines.append("    pub fn in_org(mut self, org_id: Uuid) -> Self {")
        lines.append("        self.scope.org_id = Some(org_id);")
        lines.append("        self")
        lines.append("    }")
        lines.append("")
    if has_tenant:
        lines.extend(doc_lines(
            "Address a different tenant than the client's own.\n\n"
            "§27.4 rule 3: the client's `tenant_id` is the default.", "    "))
        lines.append("    #[must_use]")
        lines.append("    pub fn for_tenant(mut self, tenant_id: Uuid) -> Self {")
        lines.append("        self.scope.tenant_id = Some(tenant_id);")
        lines.append("        self")
        lines.append("    }")
        lines.append("")

    test_cases: list[str] = []
    for opname in ops:
        body, case = emit_operation(namespace, opname, ops[opname], secrets, types)
        lines.append(body)
        test_cases.append(case)
    lines.append("}")
    body = "\n".join(lines)

    imports = ["use crate::AxiamError;", "use crate::client::AxiamClient;"]
    if "models::" in body:
        imports.append("use crate::management::models;")
    paging = [n for n in ("Page", "PageRequest", "collect_pages")
              if re.search(rf"\b{n}\b", body.split(import_marker, 1)[1])]
    if paging:
        imports.append(f"use crate::management::page::{{{', '.join(sorted(paging))}}};")
    imports.append("use crate::management::request::{Call, Verb};")
    imports.append("use crate::management::scope::Scope;")
    head = "use uuid::Uuid;\n\n" if re.search(r"\bUuid\b", body.split(import_marker, 1)[1]) else ""
    body = body.replace(import_marker, head + "\n".join(imports) + "\n", 1)
    return body, test_cases


def emit_operation(
    namespace: str,
    opname: str,
    op: dict[str, Any],
    secrets: dict[str, set[str]],
    types: Types,
) -> tuple[str, str]:
    canonical = f"{namespace}.{opname}"
    method = field_name(opname)[0]
    implicit = implicit_params(namespace, op)
    verb = {"GET": "Verb::Get", "POST": "Verb::Post", "PUT": "Verb::Put",
            "DELETE": "Verb::Delete"}[op["method"]]

    args: list[str] = []
    prelude: list[str] = []
    for p in op["path_params"]:
        if p["name"] in implicit:
            resolver = "org" if p["name"] == "org_id" else "tenant"
            prelude.append(
                f'        let {p["name"]} = self.scope.{resolver}(self.client, "{canonical}")?;'
            )
        else:
            args.append(f'{p["name"]}: {param_rust_type(p["format"])}')

    query_extra = [q for q in op["query_params"] if q["name"] not in ("offset", "limit")]
    required_q = [q for q in query_extra if q["required"]]
    optional_q = [q for q in query_extra if not q["required"]]
    filter_ty = None
    if len(optional_q) > 2:
        filter_ty = f"{pascal(namespace)}{pascal(opname)}Filter"
    for q in required_q:
        args.append(f'{field_name(q["name"])[0]}: {query_rust_type(q["type"])}')
    if filter_ty:
        args.append(f"filter: &{filter_ty}")
    else:
        for q in optional_q:
            ident = field_name(q["name"])[0]
            ty = query_rust_type(q["type"])
            args.append(f"{ident}: Option<{ty}>")
    if op["paginated"]:
        args.append("page: PageRequest")

    body_arg = None
    if op["request_body"] == "schema":
        schema = op["request_schema"]
        public = f"models::{pascal(schema)}"
        args.append(f"body: &{public}")
        if schema in secrets:
            prelude.append(f"        let body = models::{pascal(schema)}Wire::from(body);")
            prelude.append("        let body = &body;")
        body_arg = "Some(body)"
    elif op["request_body"] == "untyped":
        args.append("body: &serde_json::Value")
        body_arg = "Some(body)"

    # Query assembly.
    query_lines: list[str] = []
    seeds = [
        f'("{q["name"]}", {field_name(q["name"])[0]}.to_string())' for q in required_q
    ]
    needs_mut = bool(optional_q)
    if op["paginated"]:
        query_lines.append(
            f"        {'let mut query' if (seeds or needs_mut) else 'let query'} = page.query();"
        )
        for seed in seeds:
            query_lines.append(f"        query.push({seed});")
    elif seeds:
        # `Vec::new()` followed immediately by `push` is `vec_init_then_push`.
        query_lines.append(
            f"        {'let mut query' if needs_mut else 'let query'}: "
            f"Vec<(&'static str, String)> = vec![{', '.join(seeds)}];"
        )
    elif needs_mut:
        query_lines.append("        let mut query: Vec<(&'static str, String)> = Vec::new();")
    else:
        query_lines.append("        let query: Vec<(&'static str, String)> = Vec::new();")
    for q in optional_q:
        ident = field_name(q["name"])[0]
        src = f"filter.{ident}.as_deref()" if filter_ty else ident
        if filter_ty:
            query_lines.append(f"        if let Some(v) = {src} {{")
        else:
            query_lines.append(f"        if let Some(v) = {ident} {{")
        query_lines.append(f'            query.push(("{q["name"]}", v.to_string()));')
        query_lines.append("        }")

    public_ty, wire_ty, kind = response_type(op, secrets)
    path_expr = 'format!("{}")'.format(op["path"]) if "{" in op["path"] else f'"{op["path"]}".to_string()'

    # The export's `summary` is the method and path again, which the first
    # doc line already says. Repeating it just pushes the useful text down.
    lines = doc_lines(f"`{op['method']} {op['path']}`", "    ")
    if op["update_style"] == "replace":
        lines.extend(doc_lines(
            "\n**This is a replacement, not a patch** (§27.4 rule 5). Every "
            "field of the body is required, and what you do not carry over "
            "from a prior read is not preserved -- it is overwritten. Read "
            "first, change the field you mean, send the whole thing back.",
            "    "))
    if op["sensitive_response_fields"]:
        lines.extend(doc_lines(
            "\n**Returns secret material, once.** "
            f"`{', '.join(op['sensitive_response_fields'])}` is returned by "
            "this call and by no other; no later `get` will return it again. "
            "Discarding the result destroys the credential (§27.5 rule 3).",
            "    "))
    if op["method"] != "GET":
        lines.extend(doc_lines(
            "\nNot retried on failure (§27.4 rule 8): every write on this "
            "surface is issued exactly once, including the ones that look "
            "idempotent.", "    "))

    signature = f"    pub async fn {method}(&self"
    if args:
        signature += ", " + ", ".join(args)
    signature += f") -> Result<{public_ty}, AxiamError> {{"
    lines.append(signature)
    lines.extend(prelude)
    lines.extend(query_lines)
    lines.append("        let call = Call {")
    lines.append(f'            operation: "{canonical}",')
    lines.append(f"            verb: {verb},")
    lines.append(f'            path_template: "{op["path"]}",')
    lines.append(f"            path: {path_expr},")
    lines.append("            query: &query,")
    lines.append("        };")

    body_expr = body_arg if body_arg else "None::<&()>"
    if kind == "none":
        lines.append(f"        self.client.management_send_no_content(call, {body_expr}).await")
    elif wire_ty != public_ty:
        lines.append(
            f"        let wire: {wire_ty} = self.client.management_send(call, {body_expr}).await?;"
        )
        lines.append(f"        Ok({public_ty}::from(wire))")
    else:
        lines.append(
            f"        self.client.management_send::<_, {public_ty}>(call, {body_expr}).await"
        )
    lines.append("    }")
    lines.append("")

    if op["paginated"]:
        lines.extend(emit_list_all(method, args, canonical, public_ty))

    return "\n".join(lines), canonical


def emit_list_all(method: str, args: list[str], canonical: str, public_ty: str) -> list[str]:
    """The §27.4 rule 4 auto-paging companion for a paginated read."""
    inner = public_ty[len("Page<"):-1]
    lead = [a for a in args if a != "page: PageRequest"]
    forward = [a.split(":")[0] for a in lead]
    sig = f"    pub async fn {method}_all(&self"
    if lead:
        sig += ", " + ", ".join(lead)
    sig += f", start: PageRequest) -> Result<Vec<{inner}>, AxiamError> {{"
    out = doc_lines(
        f"Walk `{canonical}` to exhaustion, concatenating every page.\n\n"
        "The auto-paging form §27.4 rule 4 requires. It stops on an empty "
        "page even if `total` disagrees, so a misreporting server costs one "
        "wasted request rather than an unbounded loop.", "    ")
    out.append(sig)
    call_args = ", ".join(forward + ["p"]) if forward else "p"
    out.append(f"        collect_pages(start, |p| self.{method}({call_args})).await")
    out.append("    }")
    out.append("")
    return out


def emit_filters(namespace: str, nsdef: dict[str, Any]) -> str:
    """Filter structs for operations with more than two optional query parameters.

    Two loose `Option` arguments read fine; six do not -- `audit.list` takes
    six, and a call site passing `None, None, Some(x), None, None, None` is one
    a reader cannot check and a refactor silently reorders.
    """
    out: list[str] = []
    for opname, op in nsdef["operations"].items():
        optional = [
            q for q in op["query_params"] if q["name"] not in ("offset", "limit") and not q["required"]
        ]
        if len(optional) <= 2:
            continue
        rname = f"{pascal(namespace)}{pascal(opname)}Filter"
        out.extend(doc_lines(
            f"Optional filters for `{namespace}.{opname}`.\n\n"
            "Every field is `None` by default; construct with "
            "`..Default::default()` and set only what you mean to filter on."
        ))
        out.append("#[derive(Debug, Clone, Default, PartialEq, Eq)]")
        out.append(f"pub struct {rname} {{")
        for q in optional:
            ident = field_name(q["name"])[0]
            out.extend(doc_lines(f"Filter on `{q['name']}`.", "    "))
            out.append(f"    pub {ident}: Option<String>,")
        out.append("}")
        out.append("")
    return "\n".join(out)


def emit_ops_mod(reg: dict[str, Any]) -> str:
    lines = [BANNER]
    lines.append("//! One handle per §27 namespace, and the accessors that reach them.")
    lines.append("//!")
    lines.append("//! §27.2 makes this namespacing normative rather than stylistic: twenty")
    lines.append("//! namespaces have a `list` and fourteen a `get`, so flattening 146")
    lines.append("//! operations onto the client would need a disambiguating prefix invented")
    lines.append("//! once per operation -- and would bury the eight §1 methods most callers")
    lines.append("//! actually want under five times as many they do not.")
    lines.append("")
    for ns in reg["namespaces"]:
        lines.append(f"pub mod {ns};")
    lines.append("")
    lines.append("use crate::client::AxiamClient;")
    lines.append("")
    lines.append("impl AxiamClient {")
    for ns, nsdef in reg["namespaces"].items():
        rname = pascal(ns)
        lines.extend(doc_lines(
            f"The `{ns}` management namespace.\n\n{nsdef['doc']}\n\n"
            f"Acquiring the handle performs no I/O (§27.2 rule 1).", "    "))
        lines.append("    #[must_use]")
        lines.append(f"    pub fn {ns}(&self) -> {ns}::{rname}<'_> {{")
        lines.append(f"        {ns}::{rname}::new(self)")
        lines.append("    }")
        lines.append("")
    lines.append("}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Example instances
# ---------------------------------------------------------------------------
# The generated test needs two things per operation: a JSON body the server can
# plausibly answer with, and a Rust value to send. Both come from the same
# schemas the models do, which is what makes the test worth running -- it
# deserializes the server's *declared* shape into the generated type, so a
# wrong `$ref`, a missed required field, a bad enum rename or a page envelope
# classified as an object fails there rather than at a user.

EXAMPLE_UUID = "11111111-1111-4111-8111-111111111111"
EXAMPLE_TIME = "2026-08-26T00:00:00Z"


def example_json(schema: dict[str, Any], types: Types, depth: int = 0) -> Any:
    """A minimal instance satisfying `schema`: required fields only."""
    if depth > 6:
        return None
    if "$ref" in schema:
        return example_json(types.resolve(schema), types, depth + 1)
    inner = types.nullable_ref(schema)
    if inner:
        return example_json(types.schemas[inner], types, depth + 1)
    if "enum" in schema:
        return schema["enum"][0]
    variants = schema.get("oneOf") or schema.get("anyOf")
    if variants:
        for v in variants:
            if v.get("type") != "null":
                return example_json(v, types, depth + 1)
        return None
    if "allOf" in schema:
        merged: dict[str, Any] = {}
        for part in schema["allOf"]:
            got = example_json(part, types, depth + 1)
            if isinstance(got, dict):
                merged.update(got)
        return merged

    t = schema.get("type")
    if isinstance(t, list):
        t = next((x for x in t if x != "null"), None)
    if t == "object" or (t is None and schema.get("properties")):
        out: dict[str, Any] = {}
        required = set(schema.get("required", []))
        for name, prop in schema.get("properties", {}).items():
            if name in required:
                out[name] = example_json(prop, types, depth + 1)
        return out
    if t == "array":
        return []
    if t == "integer":
        return 1
    if t == "number":
        return 1.0
    if t == "boolean":
        return True
    if t == "string":
        fmt = schema.get("format")
        if fmt == "uuid":
            return EXAMPLE_UUID
        if fmt == "date-time":
            return EXAMPLE_TIME
        return "example"
    return {}


def example_response(op: dict[str, Any], types: Types) -> str:
    """The JSON the mock server answers with, as a Rust raw string literal."""
    resp = op["response"]
    if resp["kind"] == "none":
        return '""'
    one = example_json(types.schemas[resp["schema"]], types)
    if resp["kind"] == "array":
        body: Any = [one]
    elif resp["kind"] == "page":
        # `total` deliberately exceeds `items.len()` nowhere here -- the
        # auto-paging walk is asserted properly in the hand-written tests, and
        # a generated fixture claiming more would loop.
        body = {"items": [one], "total": 1, "offset": 0, "limit": 50}
    else:
        body = one
    return 'r#"' + json.dumps(body) + '"#'


def rust_literal(schema: dict[str, Any], types: Types, secrets: set[str],
                 field: str | None = None, depth: int = 0) -> str:
    """A Rust expression constructing a minimal valid value for `schema`."""
    if depth > 6:
        return "Default::default()"
    if field and field in secrets:
        return 'Sensitive::new("example".to_string())'
    if "$ref" in schema:
        return struct_literal(schema["$ref"].rsplit("/", 1)[-1], types, secrets, depth + 1)
    if types.nullable_ref(schema):
        return "None"
    if schema.get("oneOf") or schema.get("anyOf"):
        return "None"

    t = schema.get("type")
    if isinstance(t, list) and "null" in t:
        return "None"
    if t == "array":
        return "Vec::new()"
    if t == "integer":
        return "1"
    if t == "number":
        return "1.0"
    if t == "boolean":
        return "true"
    if t == "string":
        fmt = schema.get("format")
        if fmt == "uuid":
            return "example_id()"
        if fmt == "date-time":
            return f'"{EXAMPLE_TIME}".to_string()'
        return '"example".to_string()'
    if t == "object" or not schema:
        return "serde_json::json!({})"
    return "Default::default()"


def struct_literal(name: str, types: Types, secrets: set[str], depth: int = 0) -> str:
    """Construct a named model, required fields only, the rest defaulted."""
    schema = types.schemas.get(name, {})
    if "enum" in schema:
        return f"models::{pascal(name)}::{pascal(str(schema['enum'][0]))}"
    if schema.get("oneOf"):
        union = discriminated(schema, types)
        if union:
            _, value, payload = union[0]
            if "$ref" in payload:
                inner = struct_literal(
                    payload["$ref"].rsplit("/", 1)[-1], types, secrets, depth + 1
                )
                return f"models::{pascal(name)}::{pascal(str(value))}({inner})"
        return "Default::default()"

    props, required, _ = types.flatten(name)
    own = secrets if depth == 0 else set()
    if not required and props:
        # All-optional bodies derive `Default`, which is both shorter and the
        # shape §27.4 rule 5 wants callers reaching for.
        return f"models::{pascal(name)}::default()"
    # Every field, not only the required ones: the Rust struct has a field per
    # property, and an initializer that names a subset does not compile. The
    # optional ones are `None`, which is also what a caller would write.
    parts = []
    for pname in sorted(props):
        value = (
            rust_literal(props[pname], types, own, pname, depth + 1)
            if pname in required
            else "None"
        )
        parts.append(f"{field_name(pname)[0]}: {value}")
    return f"models::{pascal(name)} {{ {', '.join(parts)} }}"


def call_arguments(
    namespace: str, opname: str, op: dict[str, Any], types: Types, secrets: dict[str, set[str]]
) -> tuple[list[str], str]:
    """`(call arguments, mock path)` for one operation in the generated test."""
    implicit = implicit_params(namespace, op)
    args: list[str] = []
    route = op["path"]
    for prm in op["path_params"]:
        name = prm["name"]
        if name in implicit:
            value = "{ORG_ID}" if name == "org_id" else "{TENANT_ID}"
            route = route.replace("{" + name + "}", value)
            continue
        if prm["format"] == "uuid":
            args.append("example_id()")
            route = route.replace("{" + name + "}", "{EXAMPLE_ID}")
        else:
            args.append('"example"')
            route = route.replace("{" + name + "}", "example")

    extra = [q for q in op["query_params"] if q["name"] not in ("offset", "limit")]
    required_q = [q for q in extra if q["required"]]
    optional_q = [q for q in extra if not q["required"]]
    for _ in required_q:
        args.append('"example"')
    if len(optional_q) > 2:
        filter_ty = f"{pascal(namespace)}{pascal(opname)}Filter"
        args.append(f"&{namespace}::{filter_ty}::default()")
    else:
        args.extend("None" for _ in optional_q)
    if op["paginated"]:
        args.append("PageRequest::first(50)")

    if op["request_body"] == "schema":
        args.append(f"&{struct_literal(op['request_schema'], types, secrets.get(op['request_schema'], set()))}")
    elif op["request_body"] == "untyped":
        args.append("&serde_json::json!({})")
    return args, route


def emit_test(reg: dict[str, Any], types: Types, secrets: dict[str, set[str]]) -> str:
    """One test per namespace, reaching every operation in it.

    This exists because of the coverage floor, and because a generated surface
    with no generated test is a surface whose first caller is its first test.
    Each case mounts the response the OpenAPI schema *declares* and asserts the
    SDK deserializes it into the generated type -- so a wrong `$ref`, a missed
    required field, a bad enum rename or a page envelope classified as an
    object fails here rather than at a user.
    """
    lines = [BANNER]
    lines.append("//! Generated §27 surface conformance: every operation is reached once.")
    lines.append("//!")
    lines.append("//! Per operation: the SDK issues the registry's method against the registry's")
    lines.append("//! path, and deserializes the response shape `openapi.json` declares. Semantics")
    lines.append("//! that are not per-operation -- sparse-update key sets, secret redaction,")
    lines.append("//! error mapping, pagination walks, the manifest -- are tested by hand in the")
    lines.append("//! other `tests/management_*.rs` files.")
    lines.append("")
    lines.append('#![cfg(feature = "rest")]')
    lines.append("")
    lines.append("mod management_support;")
    lines.append("")
    lines.append("use axiam_sdk::Sensitive;")
    lines.append("use axiam_sdk::management::PageRequest;")
    lines.append("use axiam_sdk::management::models;")
    lines.append("use axiam_sdk::management::ops::*;")
    lines.append("use uuid::Uuid;")
    lines.append("use wiremock::MockServer;")
    lines.append("")
    lines.append("use management_support::{")
    lines.append("    EXAMPLE_ID, ORG_ID, TENANT_ID, expected_surface, logged_in_client, mount,")
    lines.append("};")
    lines.append("")
    lines.append("fn example_id() -> Uuid {")
    lines.append("    Uuid::parse_str(EXAMPLE_ID).expect(\"fixture id parses\")")
    lines.append("}")
    lines.append("")

    all_ops = [f"{ns}.{op}" for ns, nsd in reg["namespaces"].items() for op in nsd["operations"]]
    lines.append("/// Every operation this file exercises, in registry order.")
    lines.append("///")
    lines.append("/// §27.9: assert the count and the names, so a partial regeneration fails")
    lines.append("/// here instead of quietly shipping 140 of 146.")
    lines.append(f"const EXERCISED: [&str; {len(all_ops)}] = [")
    for name in all_ops:
        lines.append(f'    "{name}",')
    lines.append("];")
    lines.append("")
    lines.append("#[test]")
    lines.append("fn generated_surface_matches_the_registry() {")
    lines.append("    let mut expected = expected_surface();")
    lines.append("    let mut exercised: Vec<String> =")
    lines.append("        EXERCISED.iter().map(|s| (*s).to_string()).collect();")
    lines.append("    expected.sort();")
    lines.append("    exercised.sort();")
    lines.append("    assert_eq!(")
    lines.append("        exercised, expected,")
    lines.append('        "the generated surface and management-registry.json disagree"')
    lines.append("    );")
    lines.append("}")
    lines.append("")

    for namespace, nsdef in reg["namespaces"].items():
        lines.append(f"/// Reaches every operation in the `{namespace}` namespace.")
        lines.append("#[tokio::test]")
        lines.append(f"async fn {namespace}_surface() {{")
        lines.append("    let server = MockServer::start().await;")
        lines.append("    let client = logged_in_client(&server).await;")
        lines.append("")
        for opname, op in nsdef["operations"].items():
            canonical = f"{namespace}.{opname}"
            args, route = call_arguments(namespace, opname, op, types, secrets)
            body = example_response(op, types)
            status = op["response"]["status"]
            method_name = field_name(opname)[0]
            lines.append(f"    // {canonical}")
            # `format!` with nothing to substitute is `clippy::useless_format`.
            route_expr = f'&format!("{route}")' if "{" in route else f'"{route}"'
            lines.append(
                f'    mount(&server, "{op["method"]}", {route_expr}, {status}, {body}).await;'
            )
            call = f"client.{namespace}().{method_name}({', '.join(args)})"
            lines.append(f'    {call}')
            lines.append(f'        .await')
            lines.append(f'        .expect("{canonical}");')
            if op["paginated"]:
                lines.append(
                    f'    client.{namespace}().{method_name}_all('
                    + ", ".join(a for a in args if a != "PageRequest::first(50)")
                    + (", " if len(args) > 1 else "")
                    + "PageRequest::first(50))"
                )
                lines.append("        .await")
                lines.append(f'        .expect("{canonical} auto-paging");')
            lines.append("")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed output is not what this run produces")
    args = ap.parse_args()

    reg = json.loads(REGISTRY.read_text())
    spec = json.loads(OPENAPI.read_text())
    types = Types(spec)
    secrets = sensitive_map(reg)

    written: dict[Path, str] = {MODELS_OUT: emit_models(reg, types)}
    for ns, nsdef in reg["namespaces"].items():
        body, _ = emit_namespace(ns, nsdef, secrets, types)
        filters = emit_filters(ns, nsdef)
        if filters:
            body = body.replace("impl<'c>", filters + "\nimpl<'c>", 1)
        written[OPS_DIR / f"{ns}.rs"] = body
    written[OPS_DIR / "mod.rs"] = emit_ops_mod(reg)
    written[TEST_OUT] = emit_test(reg, types, secrets)

    if args.check:
        stale = [p for p, body in written.items() if not p.exists() or p.read_text() != body]
        if stale:
            for p in stale:
                print(f"FAIL: {p.relative_to(ROOT)} is stale", file=sys.stderr)
            print("run tools/gen_management.py", file=sys.stderr)
            return 1
        print(f"OK: {len(written)} generated files are current "
              f"({reg['operation_count']} operations)")
        return 0

    OPS_DIR.mkdir(parents=True, exist_ok=True)
    for path, body in written.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body if body.endswith("\n") else body + "\n")
    print(f"wrote {len(written)} files: {reg['operation_count']} operations across "
          f"{reg['namespace_count']} namespaces")
    # rustfmt is the formatting authority; generating pre-formatted text by
    # hand is a losing game and CI runs `cargo fmt --check`.
    subprocess.run(["cargo", "fmt"], cwd=ROOT, check=False)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
